/**
 * @file app_config.h
 * @brief RS485 Modbus 主机系统配置文件
 *
 * 此文件包含了 RS485 通信、Modbus 协议、硬件引脚配置等所有宏定义。
 * 修改这些配置可以调整系统行为，如波特率、地址、超时时间等。
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-08
 */

#ifndef APP_LAYER_TASK_APP_CONFIG_H
#define APP_LAYER_TASK_APP_CONFIG_H

#include "main.h"

/**
 * @defgroup RS485_Config RS485 总线配置
 * @{
 */
#define RS485_BAUDRATE                  115200U     /**< RS485 通信波特率，单位：bps */
#define RS485_ADDRESS_MASTER            0x01U       /**< 主机地址，用于 Modbus 协议中的主机标识 */
#define RS485_ADDRESS_SLAVE1            0x01U       /**< 从机1地址：与 RS485_Slave1 一致 */
#define RS485_ADDRESS_SLAVE2            0x02U       /**< 从机2地址（当前单从机测试未使用） */
#define RS485_SLAVE_COUNT               2U          /**< 当前支持两个从机 */
#define RS485_POLL_INTERVAL_MS          200U        /**< 轮询间隔时间，单位：毫秒，每次轮询之间的等待时间 */
#define RS485_RX_TIMEOUT_MS             30U         /**< 接收超时时间，单位：毫秒，等待接收数据的最长时间 */
/**
 * @defgroup Modbus_Config Modbus-RTU 主机功能配置
 * @{
 */
#define MODBUS_REG_SENSOR_START         0x0000U     /**< 传感器数据起始寄存器地址，从这个地址开始读取传感器数据 */
#define MODBUS_REG_SENSOR_COUNT         4U          /**< 从机寄存器数量：0x0000~0x0003 */
#define MODBUS_REG_CONTROL_ADDR         0x0001U     /**< 阈值寄存器地址：写入光照阈值 */
#define MODBUS_REG_ADDR_S1_THRESHOLD    0x0001U     /**< 从机1阈值寄存器地址 */
#define MODBUS_REG_ADDR_S2_SERVO_ANGLE  0x0003U     /**< 从机2舵机角度寄存器地址 */
#define MODBUS_CONTROL_OFF_VALUE        0x0000U     /**< 继电器关：写低阈值(0lux)使 lux<threshold 不成立 */
#define MODBUS_THRESHOLD_MIN            0U          /**< 从机阈值下限（单位lux） */
#define MODBUS_THRESHOLD_MAX            3300U       /**< 从机阈值上限（单位lux） */
#define MODBUS_SERVO_ANGLE_MIN          0U          /**< 从机2舵机角度下限（单位度） */
#define MODBUS_SERVO_ANGLE_MAX          180U        /**< 从机2舵机角度上限（单位度） */
/** @} */

/**
 * @defgroup GPIO_Config GPIO 引脚配置
 * @{
 */
/** LED 配置 */
#define LED_GPIO_PORT                   LED_GPIO_Port    /**< LED 引脚的 GPIO 端口 */
#define LED_GPIO_PIN                    LED_Pin          /**< LED 引脚的 GPIO 引脚 */
/** @} */

/**
 * @defgroup Offline_Config 从机离线管理配置
 * @{
 */
#define RS485_SLAVE_OFFLINE_FAIL_THRESHOLD  3U      /**< 连续失败达到该阈值后标记从机为离线状态 */
#define RS485_SLAVE_RETRY_INTERVAL_MS       1000U   /**< 离线从机的恢复探测周期，单位：毫秒 */
/** @} */

/**
 * @defgroup Diag_Config 诊断配置
 * @{
 */
#define RS485_ERROR_HISTORY_SIZE 10U  /**< 错误历史缓冲区大小，存储最近N次错误 */
#define RS485_CONSOLE_CMD_MAX_LEN 32U /**< USART2命令最大长度（含结尾符前有效字符） */
#define RS485_CONSOLE_POLL_BUDGET 16U /**< 每轮最多处理命令字节，避免挤占通信状态机 */
#define RS485_CONSOLE_RX_RING_SIZE 64U /**< 控制台中断接收环形缓冲区大小 */
#define RS485_CONSOLE_TX_TIMEOUT_MS 20U /**< 命令应答发送超时，避免阻塞 */
#define RS485_DIAG_TX_BUDGET_MS 20U /**< 诊断与控制台非阻塞发送预算，确保完整文本能够发送 */
/* RTOS 任务调度参数由配置层集中定义，避免任务代码里散落隐藏常量。 */
#define RS485_TASK_PERIOD_MS 10U /**< RS485 通信任务的周期调度间隔 */
#define RS485_DIAG_PERIOD_MS 1000U /**< 诊断任务的周期调度间隔 */
#define RS485_TASK_STACK_WORDS 512U /**< RS485 通信任务堆栈深度（按 word 计），用于容纳状态机调用链 */
#define RS485_DIAG_TASK_STACK_WORDS 512U /**< 诊断任务堆栈深度（按 word 计），用于容纳 snprintf 和串口输出 */
#define RS485_TASK_PRIORITY_RS485 3U /**< RS485 通信任务优先级 */
#define RS485_TASK_PRIORITY_DIAG 1U /**< 诊断任务优先级 */
/** @} */

/**
 * @brief RS485 错误码枚举
 */
typedef enum {
    RS485_ERR_NONE = 0,           /**< 无错误 */
    RS485_ERR_TIMEOUT,            /**< 接收超时 */
    RS485_ERR_CRC,                /**< CRC校验失败 */
    RS485_ERR_FRAME,              /**< 帧格式错误 */
    RS485_ERR_SLAVE_OFFLINE,      /**< 从机离线 */
    RS485_ERR_INVALID_RESPONSE,   /**< 无效响应 */
    RS485_ERR_RESOURCE_BUSY,      /**< 外设资源被占用或重复初始化 */
    RS485_ERR_MAX                 /**< 错误码最大值，用于边界检查 */
} RS485_ErrorCode_t;

#endif
