/**
 * @file rs485_driver.c
 * @brief RS485 驱动统一实现
 *
 * 此文件统一实现 RS485 驱动收发链路，包括 RX DMA 环形接收、IDLE + 静默 tick
 * 判帧结束、整帧提取，以及 TX DMA 异步发送与完成回调处理。
 *
 * 主要内容：
 * - 驱动内部上下文与状态机定义
 * - RX 链路（DMA/IDLE/静默判帧/取帧）
 * - TX 链路（DMA 发送/发送完成回调）
 * - 对外 API 与中断入口
 *
 * @note 此模块依赖 HAL UART 和 DMA 驱动，确保 UART 和 DMA 已正确配置。
 * @note RS485 方向控制由硬件自动完成，无需软件干预。
 * @note 帧结束判定基于 Modbus RTU 3.5 字符间隔规则。
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#include "rs485_driver.h"

#include <string.h>

#include "app_config.h"

// ==================== 私有类型与上下文 ====================

// RS485 发送状态机，用于跟踪 DMA 发送进度。
// 确保发送操作的原子性和状态一致性。
typedef enum
{
    // 空闲态：可发可收。
    RS485_TX_STATE_IDLE = 0,
    // DMA 正在发送。
    RS485_TX_STATE_DMA_BUSY
} Rs485TxState_t;

// RS485 驱动内部共享上下文，集中保存收发链路状态。
// 所有收发相关变量集中在此结构体中，便于状态管理。
typedef struct
{
    // 串口句柄，由上层初始化时注入。
    UART_HandleTypeDef *huart;

    // UART RX DMA 环形缓冲区，用于存储接收到的字节流。
    // 大小由 MODBUS_RX_DMA_BUFFER_SIZE 定义，支持环形覆盖。
    uint8_t rx_dma_buffer[MODBUS_RX_DMA_BUFFER_SIZE];
    // UART TX DMA 线性发送缓冲区，用于暂存待发送数据。
    uint8_t tx_dma_buffer[MODBUS_TX_BUFFER_SIZE];

    // 环形缓冲区读指针：指向尚未交付上层的起始位置。
    // 用于提取完整帧时确定起始索引。
    volatile uint16_t rx_read_pos;
    // 记录 IDLE 中断到来时 DMA 当前写入位置。
    // 用于计算候选帧长度。
    volatile uint16_t rx_idle_pos;
    // 标记已观测到一次串口空闲事件。
    // 用于触发静默计时。
    volatile uint8_t rx_idle_seen;
    // 标记一帧数据已经可以被主循环提取。
    // 防止重复提取同一帧。
    volatile uint8_t rx_frame_ready;
    // 当前待提取帧长度。
    // 基于读指针到 idle 指针的距离计算。
    volatile uint16_t rx_frame_length;
    // 空闲计数 tick，用于 3.5 字符间隔判定。
    // 每个 tick 代表一个字符时间。
    volatile uint16_t silence_ticks;

    // 发送状态机当前状态。
    // 确保发送操作不重叠。
    volatile Rs485TxState_t tx_state;
    // 本次 DMA 发送长度。
    // 用于校验发送完成。
    volatile uint16_t tx_length;
} Rs485DriverContext_t;

// RS485 驱动内部唯一上下文实例。
// 全局静态，确保模块内唯一。
static Rs485DriverContext_t s_driver_ctx = {0};

// ==================== RX 链路私有实现 ====================

// 计算环形缓冲区 from 到 to 的距离。
// 处理环形缓冲区的回卷情况，确保距离计算正确。
// @param from 起始位置索引。
// @param to 结束位置索引。
// @return 距离值，uint16_t 类型。
static uint16_t rs485_distance_in_ring(uint16_t from, uint16_t to)
{
    // 未回卷，直接相减。
    if (to >= from)
    {
        return (uint16_t)(to - from);
    }

    // 已回卷，尾段长度加头段长度。
    return (uint16_t)((MODBUS_RX_DMA_BUFFER_SIZE - from) + to);
}

// 复位接收链路上下文。
// 清空所有接收相关状态，确保下次接收从干净状态开始。
static void rs485_driver_rx_reset(void)
{
    s_driver_ctx.rx_read_pos = 0U;
    s_driver_ctx.rx_idle_pos = 0U;
    s_driver_ctx.rx_idle_seen = 0U;
    s_driver_ctx.rx_frame_ready = 0U;
    s_driver_ctx.rx_frame_length = 0U;
    s_driver_ctx.silence_ticks = 0U;
}

// 启动 RX DMA 与 IDLE 中断。
// 初始化 DMA 接收，并使能 IDLE 中断用于帧尾检测。
static void rs485_driver_rx_start(void)
{
    if (s_driver_ctx.huart == NULL)
    {
        return;
    }

    // 启动 DMA 接收到环形缓冲区。
    if (HAL_UART_Receive_DMA(s_driver_ctx.huart,
                             s_driver_ctx.rx_dma_buffer,
                             MODBUS_RX_DMA_BUFFER_SIZE) != HAL_OK)
    {
        // 启动失败时保持静默，等待上层重试策略。
        return;
    }

    // 关闭半传输中断，降低无效中断负担。
    __HAL_DMA_DISABLE_IT(s_driver_ctx.huart->hdmarx, DMA_IT_HT);
    // 使能 IDLE 中断，通过串口空闲来感知“可能帧尾”。
    __HAL_UART_ENABLE_IT(s_driver_ctx.huart, UART_IT_IDLE);
}

// 处理 USART IDLE 中断，记录候选帧尾。
// IDLE 中断表示串口总线空闲，可能是一帧结束的信号。
static void rs485_driver_rx_on_usart_idle_irq(void)
{
    uint16_t current_pos;

    if (s_driver_ctx.huart == NULL)
    {
        return;
    }

    if (__HAL_UART_GET_FLAG(s_driver_ctx.huart, UART_FLAG_IDLE) == RESET)
    {
        return;
    }

    if (__HAL_UART_GET_IT_SOURCE(s_driver_ctx.huart, UART_IT_IDLE) == RESET)
    {
        return;
    }

    // 清除 IDLE 标志，避免重复进入。
    __HAL_UART_CLEAR_IDLEFLAG(s_driver_ctx.huart);

    // 通过剩余计数换算 DMA 当前写入位置。
    current_pos = (uint16_t)(MODBUS_RX_DMA_BUFFER_SIZE -
                             __HAL_DMA_GET_COUNTER(s_driver_ctx.huart->hdmarx));
    if (current_pos >= MODBUS_RX_DMA_BUFFER_SIZE)
    {
        current_pos = 0U;
    }

    // 仅记录候选帧尾位置，实际整帧判定由 TIM2_CH1 静默 tick 完成。
    s_driver_ctx.rx_idle_pos = current_pos;
    s_driver_ctx.rx_idle_seen = 1U;
    s_driver_ctx.silence_ticks = 0U;
}

// 处理静默 tick，判定是否达到 3.5 字符间隔。
// 每个 tick 递增计数，到达阈值后确认帧结束。
static void rs485_driver_rx_on_silence_tick_irq(void)
{
    uint16_t frame_length;

    if ((s_driver_ctx.rx_idle_seen == 0U) || (s_driver_ctx.rx_frame_ready != 0U))
    {
        return;
    }

    s_driver_ctx.silence_ticks++;
    if (s_driver_ctx.silence_ticks < MODBUS_FRAME_END_TICKS)
    {
        return;
    }

    // 达到阈值后，按读指针到 idle 指针计算帧长度。
    frame_length = rs485_distance_in_ring(s_driver_ctx.rx_read_pos, s_driver_ctx.rx_idle_pos);
    if (frame_length == 0U)
    {
        s_driver_ctx.rx_idle_seen = 0U;
        s_driver_ctx.silence_ticks = 0U;
        return;
    }

    s_driver_ctx.rx_frame_length = frame_length;
    s_driver_ctx.rx_frame_ready = 1U;
    s_driver_ctx.rx_idle_seen = 0U;
    s_driver_ctx.silence_ticks = 0U;
}

// 从 DMA 环形缓冲区提取一帧数据。
// 拷贝完整帧到用户缓冲区，并更新读指针。
// @param frame 用户提供的帧缓冲区。
// @param frame_buf_size 缓冲区大小。
// @param frame_len 输出参数，返回实际帧长度。
// @return true 表示成功提取，false 表示无帧或缓冲区不足。
static bool rs485_driver_rx_fetch_frame(uint8_t *frame,
                                        uint16_t frame_buf_size,
                                        uint16_t *frame_len)
{
    uint16_t i;
    uint16_t length;

    if ((frame == NULL) || (frame_len == NULL))
    {
        return false;
    }

    if (s_driver_ctx.rx_frame_ready == 0U)
    {
        return false;
    }

    length = s_driver_ctx.rx_frame_length;
    if ((length == 0U) || (length > frame_buf_size))
    {
        // 长度异常时丢弃当前帧，读指针追到 idle 位置。
        s_driver_ctx.rx_read_pos = s_driver_ctx.rx_idle_pos;
        s_driver_ctx.rx_frame_ready = 0U;
        s_driver_ctx.rx_frame_length = 0U;
        return false;
    }

    // 从 DMA 环形缓冲区按顺序拷贝整帧。
    for (i = 0U; i < length; i++)
    {
        uint16_t index = (uint16_t)((s_driver_ctx.rx_read_pos + i) % MODBUS_RX_DMA_BUFFER_SIZE);
        frame[i] = s_driver_ctx.rx_dma_buffer[index];
    }

    s_driver_ctx.rx_read_pos = s_driver_ctx.rx_idle_pos;
    s_driver_ctx.rx_frame_ready = 0U;
    s_driver_ctx.rx_frame_length = 0U;

    *frame_len = length;
    return true;
}

// ==================== TX 链路私有实现 ====================

// 复位发送状态机上下文。
// 清空发送相关状态，确保下次发送从空闲开始。
static void rs485_driver_tx_reset(void)
{
    s_driver_ctx.tx_state = RS485_TX_STATE_IDLE;
    s_driver_ctx.tx_length = 0U;
}

// 处理 UART DMA 发送完成回调。
// 发送完成后自动回空闲态，允许下次发送。
// @param huart UART 句柄，用于确认是本模块的回调。
static void rs485_driver_tx_on_uart_tx_complete_irq(UART_HandleTypeDef *huart)
{
    if ((s_driver_ctx.huart == NULL) || (huart != s_driver_ctx.huart))
    {
        return;
    }

    // 自动收发模块由硬件完成方向切换，发送完成即可回空闲态。
    s_driver_ctx.tx_state = RS485_TX_STATE_IDLE;
    s_driver_ctx.tx_length = 0U;
}

// 通过 DMA 异步发送一帧数据。
// 拷贝数据到发送缓冲区，启动 DMA 发送。
// @param data 待发送数据指针。
// @param length 数据长度。
// @return true 表示发送启动成功，false 表示参数错误或状态忙。
static bool rs485_driver_tx_send(const uint8_t *data, uint16_t length)
{
    if ((s_driver_ctx.huart == NULL) || (data == NULL) || (length == 0U) ||
        (length > MODBUS_TX_BUFFER_SIZE))
    {
        return false;
    }

    if (s_driver_ctx.tx_state != RS485_TX_STATE_IDLE)
    {
        return false;
    }

    memcpy(s_driver_ctx.tx_dma_buffer, data, length);
    s_driver_ctx.tx_length = length;

    if (HAL_UART_Transmit_DMA(s_driver_ctx.huart,
                              s_driver_ctx.tx_dma_buffer,
                              s_driver_ctx.tx_length) != HAL_OK)
    {
        s_driver_ctx.tx_state = RS485_TX_STATE_IDLE;
        s_driver_ctx.tx_length = 0U;
        return false;
    }

    s_driver_ctx.tx_state = RS485_TX_STATE_DMA_BUSY;
    return true;
}

// ==================== 对外 API 实现 ====================

// 初始化 RS485 驱动。
// 注入 UART 句柄，复位收发上下文。
// @param huart 已初始化的 UART 句柄指针。
void rs485_driver_init(UART_HandleTypeDef *huart)
{
    // 保存串口句柄并复位收发上下文。
    s_driver_ctx.huart = huart;
    rs485_driver_rx_reset();
    rs485_driver_tx_reset();
}

// 启动 RS485 驱动接收链路。
// 调用后开始监听 RS485 总线上的数据。
void rs485_driver_start(void)
{
    rs485_driver_rx_start();
}

// 处理 USART IDLE 中断入口。
// 由 USART ISR 调用，用于帧尾检测。
void rs485_driver_on_usart_idle_irq(void)
{
    rs485_driver_rx_on_usart_idle_irq();
}

// 处理 UART 发送完成回调入口。
// 由 UART TX 完成 ISR 调用，用于状态机推进。
// @param huart UART 句柄。
void rs485_driver_on_uart_tx_complete_irq(UART_HandleTypeDef *huart)
{
    rs485_driver_tx_on_uart_tx_complete_irq(huart);
}

// 处理静默 tick 中断入口。
// 由定时器 ISR 调用，用于帧结束判定。
void rs485_driver_on_silence_tick_irq(void)
{
    // TIM2_CH1 周期 tick 用于收敛 IDLE 之后的静默时间判定。
    rs485_driver_rx_on_silence_tick_irq();
}

// 轮询 RS485 驱动。
// 当前实现为空，因为收发由中断和 DMA 驱动，无需轮询推进。
void rs485_driver_poll(void)
{
    // 未初始化时不处理。
    if (s_driver_ctx.huart == NULL)
    {
        return;
    }

    // 自动收发下发送流程由 DMA 回调闭环，无需轮询推进方向控制。
}

// 提取一帧接收数据。
// 从内部缓冲区拷贝完整帧到用户缓冲区。
// @param frame 用户帧缓冲区。
// @param frame_buf_size 缓冲区大小。
// @param frame_len 输出参数，返回帧长度。
// @return true 表示成功提取，false 表示无帧可用。
bool rs485_driver_fetch_frame(uint8_t *frame, uint16_t frame_buf_size, uint16_t *frame_len)
{
    return rs485_driver_rx_fetch_frame(frame, frame_buf_size, frame_len);
}

// 发送一帧数据。
// 异步启动 DMA 发送。
// @param data 待发送数据指针。
// @param length 数据长度。
// @return true 表示发送启动成功。
bool rs485_driver_send(const uint8_t *data, uint16_t length)
{
    return rs485_driver_tx_send(data, length);
}
