/**
 * @file rs485_slave.c
 * @brief Modbus 从机协议处理实现
 *
 * 此文件实现 Modbus-RTU 从机协议处理，包括 CRC 校验、寄存器读写分发、异常响应
 * 组帧以及与 RS485 驱动的数据收发协同。
 *
 * 主要内容：
 * - Modbus CRC 与请求合法性校验
 * - 0x03/0x06 功能码处理
 * - 异常响应构建与异步发送触发
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#include "rs485_slave.h"

#include "app_config.h"
#include "crc.h"
#include "mpu6050_sensor.h"
#include "rs485_driver.h"
#include "servo_control.h"

// ========================= 协议上下文与收发缓存 =========================

// Modbus 请求缓存。
static uint8_t s_request_buffer[MODBUS_MAX_ADU_LENGTH];
// Modbus 响应缓存。
static uint8_t s_response_buffer[MODBUS_MAX_ADU_LENGTH];

// ========================= CRC16 校验计算层 =========================

// 计算 Modbus RTU CRC16（多项式 0xA001，初值 0xFFFF）。
static uint16_t modbus_crc16_calculate(const uint8_t *data, uint16_t length)
{
    // CRC 累加寄存器。
    uint16_t crc = 0xFFFFU;
    // 字节循环变量。
    uint16_t i;
    // 位循环变量。
    uint8_t bit;

    // 逐字节处理。
    for (i = 0U; i < length; i++)
    {
        // 当前字节并入 CRC 低字节。
        crc ^= data[i];
        // 每个字节执行 8 次移位与异或。
        for (bit = 0U; bit < 8U; bit++)
        {
            // LSB 为 1 时先右移再异或多项式。
            if ((crc & 0x0001U) != 0U)
            {
                crc = (uint16_t)((crc >> 1U) ^ 0xA001U);
            }
            else
            {
                // LSB 为 0 时仅右移。
                crc >>= 1U;
            }
        }
    }

    // 返回 Modbus CRC16 结果。
    return crc;
}

// ====================== 寄存器映射访问层 =======================

// 读取寄存器映射值。
static uint16_t modbus_get_register_value(uint16_t reg_addr)
{
    // 0x0000：MPU6050 X 轴原始值。
    if (reg_addr == MODBUS_REG_ADDR_ACCEL_X_RAW)
    {
        return (uint16_t)mpu6050_sensor_get_accel_x_raw();
    }

    // 0x0001：MPU6050 Y 轴原始值。
    if (reg_addr == MODBUS_REG_ADDR_ACCEL_Y_RAW)
    {
        return (uint16_t)mpu6050_sensor_get_accel_y_raw();
    }

    // 0x0002：MPU6050 Z 轴原始值。
    if (reg_addr == MODBUS_REG_ADDR_ACCEL_Z_RAW)
    {
        return (uint16_t)mpu6050_sensor_get_accel_z_raw();
    }

    // 0x0003：舵机目标角度。
    if (reg_addr == MODBUS_REG_ADDR_SERVO_ANGLE)
    {
        return servo_control_get_angle();
    }

    // 未定义地址返回 0。
    return 0U;
}

// ====================== 异常响应构建层 =======================

// 组装 Modbus 异常响应帧。
static uint16_t modbus_build_exception(uint8_t slave_addr, uint8_t function_code, uint8_t exception_code)
{
    // CRC16 变量。
    uint16_t crc;

    // 从站地址。
    s_response_buffer[0] = slave_addr;
    // 异常功能码 = 原功能码 | 0x80。
    s_response_buffer[1] = (uint8_t)(function_code | 0x80U);
    // 异常码。
    s_response_buffer[2] = exception_code;

    // 计算前 3 字节 CRC。
    crc = modbus_crc16_calculate(s_response_buffer, 3U);
    // CRC 低字节。
    s_response_buffer[3] = (uint8_t)(crc & 0xFFU);
    // CRC 高字节。
    s_response_buffer[4] = (uint8_t)(crc >> 8U);

    // 异常响应固定长度 5。
    return 5U;
}

// ===================== 功能码处理层（0x03/0x06） =====================

// 处理 0x03 读保持寄存器。
static uint16_t modbus_handle_read_holding(const uint8_t *request, uint16_t length)
{
    // 起始寄存器地址。
    uint16_t reg_start;
    // 读取寄存器数量。
    uint16_t reg_count;
    // 循环变量。
    uint16_t i;
    // CRC16 变量。
    uint16_t crc;

    // 预留参数，当前实现中不直接使用。
    (void)length;

    // 解码起始地址。
    reg_start = (uint16_t)(((uint16_t)request[2] << 8U) | request[3]);
    // 解码数量。
    reg_count = (uint16_t)(((uint16_t)request[4] << 8U) | request[5]);

    // 数量非法，返回非法数据值异常 0x03。
    if ((reg_count == 0U) || (reg_count > 125U))
    {
        return modbus_build_exception(request[0], request[1], 0x03U);
    }

    // 地址越界，返回非法地址异常 0x02。
    if (((uint32_t)reg_start + (uint32_t)reg_count) > MODBUS_REGISTER_COUNT)
    {
        return modbus_build_exception(request[0], request[1], 0x02U);
    }

    // 地址回显。
    s_response_buffer[0] = request[0];
    // 功能码回显。
    s_response_buffer[1] = request[1];
    // 字节数 = 寄存器数 * 2。
    s_response_buffer[2] = (uint8_t)(reg_count * 2U);

    // 逐寄存器填充高字节在前。
    for (i = 0U; i < reg_count; i++)
    {
        // 获取寄存器值。
        uint16_t reg_value = modbus_get_register_value((uint16_t)(reg_start + i));
        // 输出偏移。
        uint16_t out_index = (uint16_t)(3U + i * 2U);

        // 数据高字节。
        s_response_buffer[out_index] = (uint8_t)(reg_value >> 8U);
        // 数据低字节。
        s_response_buffer[(uint16_t)(out_index + 1U)] = (uint8_t)(reg_value & 0xFFU);
    }

    // 对响应头和数据区计算 CRC。
    crc = modbus_crc16_calculate(s_response_buffer, (uint16_t)(3U + reg_count * 2U));
    // CRC 低字节。
    s_response_buffer[(uint16_t)(3U + reg_count * 2U)] = (uint8_t)(crc & 0xFFU);
    // CRC 高字节。
    s_response_buffer[(uint16_t)(4U + reg_count * 2U)] = (uint8_t)(crc >> 8U);

    // 总长度 = 地址+功能+字节数+数据+CRC。
    return (uint16_t)(5U + reg_count * 2U);
}

// 处理 0x06 写单寄存器。
static uint16_t modbus_handle_write_single(const uint8_t *request, uint16_t length)
{
    // 寄存器地址。
    uint16_t reg_addr;
    // 写入值。
    uint16_t reg_value;
    // CRC16。
    uint16_t crc;

    // 预留参数。
    (void)length;

    // 解码地址。
    reg_addr = (uint16_t)(((uint16_t)request[2] << 8U) | request[3]);
    // 解码值。
    reg_value = (uint16_t)(((uint16_t)request[4] << 8U) | request[5]);

    // 仅允许写舵机角度寄存器 0x0003。
    if (reg_addr != MODBUS_REG_ADDR_SERVO_ANGLE)
    {
        return modbus_build_exception(request[0], request[1], 0x02U);
    }

    // 舵机角度越界返回非法数据值异常 0x03。
    if (servo_control_is_angle_valid(reg_value) == false)
    {
        return modbus_build_exception(request[0], request[1], 0x03U);
    }

    // 生效新角度。
    servo_control_set_angle(reg_value);

    // 0x06 正常响应按标准原样回显前 6 字节。
    s_response_buffer[0] = request[0];
    s_response_buffer[1] = request[1];
    s_response_buffer[2] = request[2];
    s_response_buffer[3] = request[3];
    s_response_buffer[4] = request[4];
    s_response_buffer[5] = request[5];

    // 计算回显数据 CRC。
    crc = modbus_crc16_calculate(s_response_buffer, 6U);
    // CRC 低字节。
    s_response_buffer[6] = (uint8_t)(crc & 0xFFU);
    // CRC 高字节。
    s_response_buffer[7] = (uint8_t)(crc >> 8U);

    // 固定长度 8。
    return 8U;
}

// ===================== 请求校验与分发层 =====================

// 解析并处理一帧请求。
static void modbus_process_request(const uint8_t *request, uint16_t length)
{
    // 本地计算 CRC。
    uint16_t crc_calc;
    // 报文携带 CRC。
    uint16_t crc_recv;
    // 响应长度，0 表示不发。
    uint16_t response_length = 0U;

    // 长度过短直接丢弃。
    if (length < MODBUS_MIN_REQUEST_LENGTH)
    {
        return;
    }

    // 非本机地址不响应。
    if (request[0] != MODBUS_SLAVE_ADDRESS)
    {
        return;
    }

    // 解析帧尾 CRC（低字节在前）。
    crc_recv = (uint16_t)(((uint16_t)request[length - 1U] << 8U) | request[length - 2U]);
    // 计算接收区前 N-2 字节 CRC。
    crc_calc = modbus_crc16_calculate(request, (uint16_t)(length - 2U));

    // CRC 不一致则丢弃。
    if (crc_calc != crc_recv)
    {
        return;
    }

    // 分发功能码 0x03。
    if (request[1] == MODBUS_FUNC_READ_HOLDING)
    {
        // 标准请求长度必须为 8。
        if (length != 8U)
        {
            response_length = modbus_build_exception(request[0], request[1], 0x03U);
        }
        else
        {
            response_length = modbus_handle_read_holding(request, length);
        }
    }
    // 分发功能码 0x06。
    else if (request[1] == MODBUS_FUNC_WRITE_SINGLE)
    {
        // 标准请求长度必须为 8。
        if (length != 8U)
        {
            response_length = modbus_build_exception(request[0], request[1], 0x03U);
        }
        else
        {
            response_length = modbus_handle_write_single(request, length);
        }
    }
    else
    {
        // 不支持功能码，异常 0x01。
        response_length = modbus_build_exception(request[0], request[1], 0x01U);
    }

    // 需要响应时交由 RS485 驱动异步发送。
    if (response_length > 0U)
    {
        (void)rs485_driver_send(s_response_buffer, response_length);
    }
}

// ======================== 对外接口层 ========================

void rs485_slave_init(void)
{
    // 协议层当前无额外初始化状态。
}

void rs485_slave_poll(void)
{
    // 取到的请求长度。
    uint16_t request_length;

    // 轮询 RS485 状态机，推进 DE 切换和 DMA 发送流程。
    rs485_driver_poll();

    // printf("request_length: %u\r\n", request_length);
    // 无完整帧则直接返回。
    if (rs485_driver_fetch_frame(s_request_buffer, MODBUS_MAX_ADU_LENGTH, &request_length) == false)
    {
        return;
    }

    // 处理收到的完整请求。
    modbus_process_request(s_request_buffer, request_length);
}

void rs485_slave_on_usart_idle_irq(void)
{
    // 串口空闲中断交给底层驱动记录候选帧尾。
    rs485_driver_on_usart_idle_irq();
}

void rs485_slave_on_uart_tx_complete_irq(UART_HandleTypeDef *huart)
{
    // 发送完成中断交给底层驱动处理后置延时。
    rs485_driver_on_uart_tx_complete_irq(huart);
}

void rs485_slave_on_silence_tick_irq(void)
{
    // TIM2_CH1 比较事件驱动静默 tick，参与 Modbus 帧结束收敛判定。
    rs485_driver_on_silence_tick_irq();
}
