/**
 * @file task_app.c
 * @brief 应用主流程实现
 *
 * 此文件实现从机应用主流程，包括系统初始化顺序、主循环轮询以及外设中断回调
 * 到业务模块的转发逻辑。
 *
 * 主要内容：
 * - 应用初始化与模块启动流程
 * - 主循环协议轮询逻辑
 * - USART/UART/TIM 中断回调转发
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#include "task_app.h"

#include "app_config.h"
#include "mpu6050_sensor.h"
#include "rs485_slave.h"
#include "rs485_driver.h"
#include "servo_control.h"

#include "i2c.h"

#include <stdio.h>

// USART2 诊断打印时间戳，控制输出节拍避免高频阻塞。
static uint32_t s_diag_last_tick_ms = 0U;

// 从机2独立测试：通过 USART2 输出 MPU 与舵机状态快照。
static void app_diag_print_usart2(void)
{
#if (APP_USART2_DIAG_ENABLE != 0U)
    // 本地快照变量，先读取再统一格式化输出，减少读取时序差异。
    int16_t accel_x_raw;
    int16_t accel_y_raw;
    int16_t accel_z_raw;
    uint16_t servo_angle_deg;
    uint8_t servo_angle_valid;
    uint32_t mpu_comm_ok_cnt;
    uint32_t mpu_comm_fail_cnt;
    uint32_t now_ms;
    int msg_len;
    char msg_buf[160];

    // 使用 HAL tick 做限频，避免主循环每次都执行串口发送。
    now_ms = HAL_GetTick();
    if ((now_ms - s_diag_last_tick_ms) < APP_USART2_DIAG_INTERVAL_MS)
    {
        return;
    }
    s_diag_last_tick_ms = now_ms;

    // 采样当前缓存值：MPU 三轴、舵机角度、I2C 通信统计。
    accel_x_raw = mpu6050_sensor_get_accel_x_raw();
    accel_y_raw = mpu6050_sensor_get_accel_y_raw();
    accel_z_raw = mpu6050_sensor_get_accel_z_raw();
    servo_angle_deg = servo_control_get_angle();
    servo_angle_valid = (servo_control_is_angle_valid(servo_angle_deg) == true) ? 1U : 0U;
    mpu_comm_ok_cnt = mpu6050_sensor_get_comm_ok_cnt();
    mpu_comm_fail_cnt = mpu6050_sensor_get_comm_fail_cnt();

    // 输出统一状态行，便于串口工具直接观察是否稳定联通。
    msg_len = snprintf(msg_buf,
                       sizeof(msg_buf),
                       "S2 AX=%d AY=%d AZ=%d SERVO=%u SERVO_OK=%u I2C_OK=%lu I2C_FAIL=%lu\r\n",
                       (int)accel_x_raw,
                       (int)accel_y_raw,
                       (int)accel_z_raw,
                       (unsigned int)servo_angle_deg,
                       (unsigned int)servo_angle_valid,
                       (unsigned long)mpu_comm_ok_cnt,
                       (unsigned long)mpu_comm_fail_cnt);
    if (msg_len > 0)
    {
        // 诊断输出使用 USART2，与 RS485 通信串口 USART1 分离。
        (void)HAL_UART_Transmit(&huart2,
                                (uint8_t *)msg_buf,
                                (uint16_t)msg_len,
                                APP_USART2_DIAG_TX_TIMEOUT_MS);
    }
#endif
}

// 应用初始化阶段只做模块启动和依赖绑定，不在此执行任何阻塞轮询。
void app_main_init(void)
{
    // 初始化舵机控制模块，改为 TIM3_CH1 输出 50Hz PWM。
    servo_control_init(&htim3, TIM_CHANNEL_1);

    // 启动 TIM2_CH1 比较中断，作为 Modbus 帧结束静默计时节拍。
    (void)HAL_TIM_OC_Start_IT(&htim2, TIM_CHANNEL_1);
    // 启动 TIM2 基本计数中断，使 CH1 比较事件持续产生。
    (void)HAL_TIM_Base_Start_IT(&htim2);

    // 初始化 MPU6050 传感器通信模块。
    mpu6050_sensor_init(&hi2c1);

    // 自检模式下不启动 RS485 通信，避免总线链路被诊断代码干扰。
#if (APP_SELF_TEST_USE_USART1_DEBUG == 0U)
    // 初始化 RS485 驱动并启动 DMA 接收。
    rs485_driver_init(&huart1);
    rs485_driver_start();

    // 初始化 Modbus 从机协议层。
    rs485_slave_init();
#endif
}

// 应用轮询阶段：先更新传感器缓存，再推进协议层状态机。
void app_main_poll(void)
{
    // 周期读取 MPU6050 原始加速度数据并更新缓存。
    mpu6050_sensor_poll();

    // 从机2独立联调阶段，通过 USART2 周期打印关键状态。
    app_diag_print_usart2();

#if (APP_SELF_TEST_USE_USART1_DEBUG == 0U)
    // 主循环中仅做轻量轮询，不在中断执行重处理。
    rs485_slave_poll();
#endif

}

// USART1 IDLE 回调只做事件转发，真正解析和回复在主循环中完成。
void app_main_on_usart_idle_irq(void)
{
    // USART IDLE 中断：记录帧候选尾。
    rs485_slave_on_usart_idle_irq();
}

// UART 发送完成回调用于通知 RS485 驱动退出发送忙态。
void app_main_on_uart_tx_cplt_irq(UART_HandleTypeDef *huart)
{
    // UART DMA 发送完成中断：通知协议层完成发送收尾。
    rs485_slave_on_uart_tx_complete_irq(huart);
}

// TIM2 Update 事件当前未使用，保留为空实现以便后续扩展定时任务。
void app_main_on_tim2_irq_tick(void)
{
    // 预留：TIM2 更新事件处理。
}

// TIM2 OC 事件用于 CH1 静默计时，驱动 Modbus 帧结束判定。
void app_main_on_tim2_oc_elapsed_irq(TIM_HandleTypeDef *htim)
{
    // 空指针或非 TIM2 事件直接返回。
    if ((htim == NULL) || (htim->Instance != TIM2))
    {
        return;
    }

    // 仅 CH1 比较事件用于 Modbus 静默 tick 收敛。
    if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_1)
    {
        rs485_slave_on_silence_tick_irq();
        return;
    }
}
