 /**
 * @file task_rs485.c
 * @brief RS485 Modbus 主机任务实现
 *
 * 此文件实现了 RS485 总线上的 Modbus-RTU 主机功能，包括非阻塞状态机通信、
 * 从机轮询、离线管理、超时重试等。系统支持一主二从配置，自动采集传感器数据
 * 并根据数据控制从机状态。
 *
 * 主要特性：
 * - 非阻塞轮询状态机，避免主循环阻塞
 * - 从机在线/离线状态管理，自动恢复
 * - 完整的超时和重试机制
 * - 数组越界和参数校验防护
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-08
 */

#include "layer_task/task_rs485.h"  // 包含任务层公开接口
#include "layer_app/rs485_console.h"  // 包含应用层控制台接口
#include "layer_middle/rs485_scheduler.h"  // 包含中间层轮询调度接口
#include "layer_middle/rs485_protocol.h"  // 包含中间层协议定义接口
#include "layer_middle/rs485_codec.h"  // 包含中间层编解码接口
#include "layer_driver/rs485_lock.h"  // 包含底层临界区抽象接口
#include "layer_driver/uart2_tx_lock.h"  // 包含 USART2 发送互斥量接口
#include "layer_driver/app_preflight.h"  // 包含底层预检与资源锁接口
#include "layer_task/app_config.h"  // 包含任务层共享配置
#include "usart.h"  // 包含USART头文件
#include <string.h>  // 字符串处理用于缓存清零和控制台格式化输出。
#include <stdio.h>   // 标准库仅用于诊断输出格式化，不参与通信主路径。

/* ========================= 私有宏与通信资源划分 ========================= */
/* 串口职责划分：RS485 通信使用 USART1，诊断输出使用 USART2。 */
#define RS485_COMM_UART_HANDLE          huart1  // RS485 通信使用的 UART 句柄
#define RS485_DIAG_UART_HANDLE          huart2  // 诊断输出使用的 UART 句柄

/* 0x03 读响应长度：地址 + 功能码 + 字节数 + 数据 + CRC。 */
#define MODBUS_RSP_READ_LEN             (uint16_t)(5U + MODBUS_REG_SENSOR_COUNT * 2U)

/*
 * 接收窗口长度：
 * - 兼容“请求回显 + 响应帧”连续到达的情况；
 * - 避免只按响应长度分配缓冲导致真实响应被截断。
 */
#define RS485_RX_WINDOW_LEN             (uint16_t)(MODBUS_REQ_WRITE_LEN + MODBUS_RSP_READ_LEN)

/* 同一从机事务失败时的重试次数（不含首次发送）。 */
#define RS485_MAX_RETRY                 2U

#ifndef RS485_SLAVE_OFFLINE_FAIL_THRESHOLD
#define RS485_SLAVE_OFFLINE_FAIL_THRESHOLD  3U  // 连续失败达到该阈值后标记离线。
#endif

#ifndef RS485_SLAVE_RETRY_INTERVAL_MS
#define RS485_SLAVE_RETRY_INTERVAL_MS       1000U  // 离线从机的恢复探测周期。
#endif

/* ========================= 内部上下文：运行态、诊断态、从机缓存 ========================= */
typedef struct {
    uint8_t poll_index;
    uint32_t last_poll_tick;
} RS485_PollContext_t;

typedef struct {
    uint32_t comm_ok_cnt;
    uint32_t comm_fail_cnt;
    RS485_ErrorCode_t error_history[RS485_ERROR_HISTORY_SIZE];
    uint8_t error_history_index;
} RS485_DiagContext_t;

typedef struct {
    uint16_t regs[RS485_SLAVE_COUNT][MODBUS_REG_SENSOR_COUNT];
    uint16_t control_target[RS485_SLAVE_COUNT];
    uint8_t manual_write_pending[RS485_SLAVE_COUNT];
    uint16_t manual_write_value[RS485_SLAVE_COUNT];
    uint8_t online[RS485_SLAVE_COUNT];
    uint8_t fail_streak[RS485_SLAVE_COUNT];
    uint32_t retry_tick[RS485_SLAVE_COUNT];
} RS485_SlaveContext_t;

typedef struct {
    uint8_t comm_state;
    uint8_t active_slave_idx;
    uint8_t active_slave_addr;
    uint8_t active_phase;
    uint8_t active_probe_only;
    uint8_t retry_left;
    uint16_t tx_len;
    uint16_t rx_len;
    uint16_t tx_idx;
    uint16_t rx_idx;
    uint16_t active_control_val;
    uint32_t state_deadline_tick;
    uint8_t tx_buf[MODBUS_REQ_WRITE_LEN];
    uint8_t rx_buf[RS485_RX_WINDOW_LEN];
} RS485_TransactionContext_t;

typedef struct {
    RS485_PollContext_t poll;
    RS485_DiagContext_t diag;
    RS485_SlaveContext_t slave;
    RS485_TransactionContext_t txn;
} RS485_Context_t;

/* 所有运行态都收拢到一个内部上下文，避免几十个散落静态变量互相穿插。 */
static RS485_Context_t s_ctx = {0};

/* ========================= 私有类型与前向声明 ========================= */
/* 前向声明只保留真正跨函数依赖的内部工具，避免在实现区反复展开。 */
static void RS485_ClearRxResidual(void);  // 清理残留接收数据。
static void RS485_RecordError(RS485_ErrorCode_t err);  // 记录错误到历史缓冲区。
static void RS485_HandleTransactionSuccess(void);  // 统一处理成功路径。
static void RS485_HandleTransactionFailure(uint32_t now, RS485_ErrorCode_t err);  // 统一处理失败路径。
static uint8_t RS485_SlaveIndexFromAddr(uint8_t slave_addr, uint8_t *out_idx);  // 地址转从机索引。
static uint8_t RS485_HandleReadFrameAndStore(uint8_t slave_addr, const uint8_t *rx_buf);  // 解析读响应并落地缓存。
static uint8_t RS485_IsManualWriteValueValid(uint8_t slave_idx, uint16_t value);  // 校验不同从机的手动写值边界。
static uint8_t RS485_GetManualWriteRegAddr(uint8_t slave_idx, uint16_t *out_reg_addr);  // 获取不同从机的手动写寄存器地址。
static uint8_t RS485_TryHandleRxWindow(uint32_t now);  // 在接收窗口内滑窗匹配合法响应。

/* ========================= 私有状态：轮询地址表 ========================= */
/* 地址表集中维护，轮询顺序固定为从机1 -> 从机2。 */
static const uint8_t s_slave_table[RS485_SLAVE_COUNT] = {
    RS485_ADDRESS_SLAVE1  // 从机1地址
#if (RS485_SLAVE_COUNT > 1U)
    , RS485_ADDRESS_SLAVE2  // 从机2地址
#endif
};

/* 通信状态机只在本文件内部使用，枚举放在这里避免外部看到实现细节。 */
typedef enum {
    RS485_COMM_IDLE = 0,   // 空闲状态，等待开始新事务
    RS485_COMM_TX,         // 发送状态，正在发送数据
    RS485_COMM_WAIT_TC,    // 等待发送完成状态
    RS485_COMM_RX          // 接收状态，正在接收数据
} RS485_CommState_t;

/* ========================= 私有状态：兼容旧实现的底层缓冲 ========================= */
/* 事务缓冲区是内部上下文的一部分，保留单次事务生命周期，不向外暴露。 */

/* ========================= 私有工具函数：链路与解析基础能力 ========================= */

/*
 * @brief 清理残留接收数据，避免上一个异常帧干扰当前事务。
 */
static void RS485_ClearRxResidual(void)
{
    uint8_t guard = 0U;  // 保护计数，避免卡在异常 RXNE 状态。

    while ((__HAL_UART_GET_FLAG(&RS485_COMM_UART_HANDLE, UART_FLAG_RXNE) != RESET) && (guard < 32U)) {
        (void)RS485_COMM_UART_HANDLE.Instance->DR;  // 直接读 DR 丢弃残留字节。
        guard++;
    }

    __HAL_UART_CLEAR_OREFLAG(&RS485_COMM_UART_HANDLE);  // 残留数据清空后同步清除 ORE。
}

/*
 * @brief 记录错误到历史缓冲区
 * @param err 错误码
 */
static void RS485_RecordError(RS485_ErrorCode_t err)
{
    s_ctx.diag.error_history[s_ctx.diag.error_history_index] = err;  // 以环形缓冲方式记录最近错误。
    s_ctx.diag.error_history_index = (s_ctx.diag.error_history_index + 1U) % RS485_ERROR_HISTORY_SIZE;
}

/*
 * @brief 地址转从机索引，失败返回0。
 */
static uint8_t RS485_SlaveIndexFromAddr(uint8_t slave_addr, uint8_t *out_idx)
{
    uint8_t i;  // 轮询表索引。

    if (out_idx == 0) {
        return 0U;
    }

    for (i = 0U; i < RS485_SLAVE_COUNT; i++) {
        if (s_slave_table[i] == slave_addr) {
            *out_idx = i;
            return 1U;
        }
    }

    return 0U;
}

/*
 * @brief 解析 0x03 响应并写入从机缓存。
 */
static uint8_t RS485_HandleReadFrameAndStore(uint8_t slave_addr, const uint8_t *rx_buf)
{
    uint8_t idx;  // 命中从机索引。
    uint8_t reg_i;  // 寄存器复制索引。
    uint16_t parsed_regs[MODBUS_REG_SENSOR_COUNT] = {0U};  // 先解析到临时缓存，成功后再写入主缓存。

    if (RS485_SlaveIndexFromAddr(slave_addr, &idx) == 0U) {
        return 0U;
    }

    if (idx >= RS485_SLAVE_COUNT) {
        return 0U;
    }

    if ((MODBUS_REG_SENSOR_COUNT == 0U) || (MODBUS_REG_SENSOR_COUNT > 125U)) {
        return 0U;
    }

    /* 读响应必须同时满足地址、功能码、长度和 CRC 校验。 */
    if (RS485_CodecParseReadResponse(slave_addr,
                                     MODBUS_REG_SENSOR_COUNT,
                                     rx_buf,
                                     MODBUS_RSP_READ_LEN,
                                     parsed_regs,
                                     MODBUS_REG_SENSOR_COUNT) == 0U) {
        return 0U;
    }

    for (reg_i = 0U; reg_i < MODBUS_REG_SENSOR_COUNT; reg_i++) {
        s_ctx.slave.regs[idx][reg_i] = parsed_regs[reg_i];
    }

    return 1U;
}

/*
 * @brief 校验手动写值是否合法。
 *
 * 从机1手动写用于阈值，范围由阈值宏定义约束；
 * 从机2手动写用于舵机角度，范围由角度宏定义约束。
 */
static uint8_t RS485_IsManualWriteValueValid(uint8_t slave_idx, uint16_t value)
{
    if (slave_idx == 0U) {
        if ((value < MODBUS_THRESHOLD_MIN) || (value > MODBUS_THRESHOLD_MAX)) {
            return 0U;
        }
        return 1U;
    }

    if (slave_idx == 1U) {
        if ((value < MODBUS_SERVO_ANGLE_MIN) || (value > MODBUS_SERVO_ANGLE_MAX)) {
            return 0U;
        }
        return 1U;
    }

    return 0U;
}

/*
 * @brief 获取目标从机手动写操作对应的 Modbus 寄存器地址。
 */
static uint8_t RS485_GetManualWriteRegAddr(uint8_t slave_idx, uint16_t *out_reg_addr)
{
    if (out_reg_addr == 0) {
        return 0U;
    }

    if (slave_idx == 0U) {
        *out_reg_addr = MODBUS_REG_ADDR_S1_THRESHOLD;
        return 1U;
    }

    if (slave_idx == 1U) {
        *out_reg_addr = MODBUS_REG_ADDR_S2_SERVO_ANGLE;
        return 1U;
    }

    return 0U;
}

/* ========================= 私有工具函数：事务控制与调度 ========================= */

/*
 * @brief 启动一次发送阶段，不阻塞主循环。
 *
 * 发送准备：
 * - 重置发送和接收索引
 * - 清空接收缓冲区
 * - 清除残留接收数据和传输完成标志
 * - 设置超时时间
 * - 进入发送状态
 *
 * @param now 当前时间戳
 * @return 1=启动成功，0=参数错误
 */
static uint8_t RS485_StartTxStage(uint32_t now)
{
    if ((s_ctx.txn.tx_len == 0U) || (s_ctx.txn.tx_len > sizeof(s_ctx.txn.tx_buf))) {
        return 0U;
    }

    /* 每次事务开始前重置收发索引和残留缓冲，避免上一帧污染当前事务。 */
    s_ctx.txn.tx_idx = 0U;
    s_ctx.txn.rx_idx = 0U;
    memset(s_ctx.txn.rx_buf, 0, sizeof(s_ctx.txn.rx_buf));

    RS485_ClearRxResidual();
    __HAL_UART_CLEAR_FLAG(&RS485_COMM_UART_HANDLE, UART_FLAG_TC);

    s_ctx.txn.state_deadline_tick = now + RS485_RX_TIMEOUT_MS;
    s_ctx.txn.comm_state = RS485_COMM_TX;

    return 1U;
}

/*
 * @brief 轮询调度推进：在线从机读/写双相位，离线恢复仅做读探测。
 *
 * 调度逻辑：
 * - 在线从机：读相位后切换到写相位，写完成后切换到下一从机
 * - 离线从机：仅执行读探测，完成后切换到下一从机
 * - 确保轮询索引在有效范围内循环
 */
static void RS485_AdvancePollSchedule(void)
{
    s_ctx.poll.poll_index = RS485_SchedAdvancePollIndex(s_ctx.txn.active_slave_idx,
                                               s_ctx.txn.active_probe_only,
                                               RS485_SLAVE_COUNT);
}

/*
 * @brief 结束当前事务并回到空闲态。
 */
static void RS485_EndTransaction(void)
{
    /* 事务结束后恢复到安全空闲态，避免残留状态影响下一轮轮询。 */
    s_ctx.txn.comm_state = RS485_COMM_IDLE;
    s_ctx.txn.tx_idx = 0U;
    s_ctx.txn.rx_idx = 0U;
    s_ctx.txn.tx_len = 0U;
    s_ctx.txn.rx_len = 0U;
    s_ctx.txn.active_slave_idx = 0xFFU;
    s_ctx.txn.active_slave_addr = 0U;
    s_ctx.txn.active_phase = 0U;
    s_ctx.txn.active_probe_only = 0U;
    s_ctx.txn.active_control_val = MODBUS_CONTROL_OFF_VALUE;
    s_ctx.txn.retry_left = 0U;
}

/*
 * @brief 在接收窗口中滑窗匹配合法响应帧。
 *
 * 设计意图：
 * - 允许窗口前部存在请求回显字节；
 * - 在窗口内逐偏移尝试协议解析，命中即成功；
 * - 窗口写满仍无合法响应则判定失败。
 */
static uint8_t RS485_TryHandleRxWindow(uint32_t now)
{
    uint16_t offset;
    uint16_t max_offset;

    if (s_ctx.txn.rx_len == 0U) {
        RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
        return 1U;
    }

    if (s_ctx.txn.rx_idx < s_ctx.txn.rx_len) {
        return 0U;
    }

    max_offset = (uint16_t)(s_ctx.txn.rx_idx - s_ctx.txn.rx_len);

    for (offset = 0U; offset <= max_offset; offset++) {
        const uint8_t *candidate = &s_ctx.txn.rx_buf[offset];

        if (s_ctx.txn.active_phase == 0U) {
            if (RS485_HandleReadFrameAndStore(s_ctx.txn.active_slave_addr, candidate) != 0U) {
                RS485_HandleTransactionSuccess();
                return 1U;
            }
        } else {
            uint16_t write_reg_addr;

            if (RS485_GetManualWriteRegAddr(s_ctx.txn.active_slave_idx, &write_reg_addr) == 0U) {
                RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
                return 1U;
            }

            if (RS485_CodecParseWriteResponse(s_ctx.txn.active_slave_addr,
                                              write_reg_addr,
                                              s_ctx.txn.active_control_val,
                                              candidate,
                                              MODBUS_RSP_WRITE_LEN) != 0U) {
                RS485_HandleTransactionSuccess();
                return 1U;
            }
        }
    }

    if (s_ctx.txn.rx_idx >= sizeof(s_ctx.txn.rx_buf)) {
        RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
        return 1U;
    }

    return 0U;
}

/*
 * @brief 响应处理成功路径。
 *
 * 成功处理：
 * - 标记从机为在线状态，清空失败计数
 * - 增加成功通信计数
 * - 推进轮询调度到下一阶段
 * - 结束当前事务，回到空闲状态
 */
static void RS485_HandleTransactionSuccess(void)
{
    if ((s_ctx.txn.active_phase == 1U) && (s_ctx.txn.active_slave_idx < RS485_SLAVE_COUNT)) {
        s_ctx.slave.manual_write_pending[s_ctx.txn.active_slave_idx] = 0U;
    }

    if (s_ctx.txn.active_slave_idx < RS485_SLAVE_COUNT) {
        RS485_SchedMarkSlaveSuccess(s_ctx.txn.active_slave_idx,
                                    RS485_SLAVE_COUNT,
                                    s_ctx.slave.online,
                                    s_ctx.slave.fail_streak);
    }

    s_ctx.diag.comm_ok_cnt++;
    RS485_AdvancePollSchedule();
    RS485_EndTransaction();
}

/*
 * @brief 响应处理失败路径，含有限重试与离线标记。
 *
 * 失败处理：
 * - 如果还有重试次数，减少计数并重新启动发送
 * - 如果重试耗尽，标记从机失败，增加连续失败计数
 * - 当失败次数达到阈值时，标记从机为离线并设置重试时间
 * - 增加失败通信计数
 * - 推进轮询调度
 * - 结束事务
 *
 * @param now 当前时间戳，用于设置离线重试时间
 * @param err 错误码
 */
static void RS485_HandleTransactionFailure(uint32_t now, RS485_ErrorCode_t err)
{
    RS485_RecordError(err);

    if (s_ctx.txn.retry_left > 0U) {
        s_ctx.txn.retry_left--;
        if (RS485_StartTxStage(now) != 0U) {
            return;
        }
    }

    if (s_ctx.txn.active_slave_idx < RS485_SLAVE_COUNT) {
        RS485_SchedMarkSlaveFailure(s_ctx.txn.active_slave_idx,
                                    RS485_SLAVE_COUNT,
                                    s_ctx.slave.online,
                                    s_ctx.slave.fail_streak,
                                    s_ctx.slave.retry_tick,
                                    now,
                                    RS485_SLAVE_OFFLINE_FAIL_THRESHOLD,
                                    RS485_SLAVE_RETRY_INTERVAL_MS);
    }

    s_ctx.diag.comm_fail_cnt++;
    RS485_AdvancePollSchedule();
    RS485_EndTransaction();
}

/*
 * @brief 启动新事务（按当前轮询策略选择从机与相位）。
 *
 * 根据轮询调度选择下一个要通信的从机：
 * - 优先选择在线从机进行读/写双相位操作
 * - 对离线从机进行读探测以恢复连接
 * - 构建相应的 Modbus 请求帧并启动发送
 *
 * @param now 当前时间戳（HAL_GetTick()返回值）
 */
static void RS485_TryStartTransaction(uint32_t now)
{
    uint8_t idx;  // 本轮选中的从机索引。
    uint16_t write_reg_addr;

    if (RS485_SchedSelectNextSlave(now,
                                   s_ctx.poll.poll_index,
                                   RS485_SLAVE_COUNT,
                                   s_ctx.slave.online,
                                   s_ctx.slave.retry_tick,
                                   &idx) == 0U) {
        return;
    }

    if (idx >= RS485_SLAVE_COUNT) {
        return;
    }

    s_ctx.txn.active_slave_idx = idx;
    s_ctx.txn.active_slave_addr = s_slave_table[idx];
    s_ctx.txn.active_probe_only = (s_ctx.slave.online[idx] == 0U) ? 1U : 0U;

    /*
     * 在线从机存在待写请求时进入写相位。
     * 这样 USART2 控制台可以统一下发从机1阈值和从机2舵机角度请求。
     */
    if ((s_ctx.txn.active_probe_only == 0U) &&
        (s_ctx.slave.manual_write_pending[idx] != 0U)) {
        s_ctx.txn.active_phase = 1U;
    } else {
        s_ctx.txn.active_phase = 0U;
    }

    s_ctx.txn.retry_left = RS485_MAX_RETRY;

    if (s_ctx.txn.active_phase == 0U) {
        if (RS485_CodecBuildReadRequest(s_ctx.txn.active_slave_addr,
                                        MODBUS_REG_SENSOR_START,
                                        MODBUS_REG_SENSOR_COUNT,
                                        s_ctx.txn.tx_buf,
                                        sizeof(s_ctx.txn.tx_buf)) == 0U) {
            RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
            return;
        }

        s_ctx.txn.tx_len = MODBUS_REQ_READ_LEN;
        s_ctx.txn.rx_len = MODBUS_RSP_READ_LEN;
    } else {
        if (s_ctx.txn.active_slave_idx >= RS485_SLAVE_COUNT) {
            RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
            return;
        }

        if (RS485_GetManualWriteRegAddr(s_ctx.txn.active_slave_idx, &write_reg_addr) == 0U) {
            RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
            return;
        }

        /* 手动控制路径：使用串口助手下发并排队的控制值。 */
        s_ctx.slave.control_target[s_ctx.txn.active_slave_idx] = s_ctx.slave.manual_write_value[s_ctx.txn.active_slave_idx];
        s_ctx.txn.active_control_val = s_ctx.slave.control_target[s_ctx.txn.active_slave_idx];

        if (RS485_IsManualWriteValueValid(s_ctx.txn.active_slave_idx, s_ctx.txn.active_control_val) == 0U) {
            RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
            return;
        }

        if (RS485_CodecBuildWriteRequest(s_ctx.txn.active_slave_addr,
                                         write_reg_addr,
                                         s_ctx.txn.active_control_val,
                                         s_ctx.txn.tx_buf,
                                         sizeof(s_ctx.txn.tx_buf)) == 0U) {
            RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
            return;
        }

        s_ctx.txn.tx_len = MODBUS_REQ_WRITE_LEN;
        s_ctx.txn.rx_len = MODBUS_RSP_WRITE_LEN;
    }

    if ((s_ctx.txn.rx_len == 0U) || (s_ctx.txn.rx_len > sizeof(s_ctx.txn.rx_buf))) {
        RS485_HandleTransactionFailure(now, RS485_ERR_INVALID_RESPONSE);
        return;
    }

    s_ctx.poll.last_poll_tick = now;
    (void)RS485_StartTxStage(now);
}

/* ========================= 公开接口：初始化、运行与诊断 ========================= */

/* 初始化 RS485：自动收发模块无需软件方向切换，轮询从机表从第一个地址开始。 */
uint8_t Task_RS485_Init(void)
{
    uint8_t i;  // 从机遍历索引。

    /* 先锁定通信与诊断串口资源，避免后续模块重复占用导致行为不确定。 */
    if (App_PreflightLockResource(APP_RESOURCE_USART1) == 0U) {
        RS485_RecordError(RS485_ERR_RESOURCE_BUSY);
        s_ctx.diag.comm_fail_cnt++;
        return 0U;
    }

    if (App_PreflightLockResource(APP_RESOURCE_USART2) == 0U) {
        App_PreflightUnlockResource(APP_RESOURCE_USART1);
        RS485_RecordError(RS485_ERR_RESOURCE_BUSY);
        s_ctx.diag.comm_fail_cnt++;
        return 0U;
    }

    s_ctx.poll.poll_index = 0U;
    s_ctx.poll.last_poll_tick = HAL_GetTick();
    s_ctx.diag.comm_ok_cnt = 0U;
    s_ctx.diag.comm_fail_cnt = 0U;
    s_ctx.txn.comm_state = RS485_COMM_IDLE;
    s_ctx.txn.active_slave_idx = 0xFFU;
    s_ctx.txn.active_slave_addr = 0U;
    s_ctx.txn.active_phase = 0U;
    s_ctx.txn.active_probe_only = 0U;
    s_ctx.txn.retry_left = 0U;
    s_ctx.txn.tx_len = 0U;
    s_ctx.txn.rx_len = 0U;
    s_ctx.txn.tx_idx = 0U;
    s_ctx.txn.rx_idx = 0U;
    s_ctx.txn.state_deadline_tick = 0U;

    /* 这里把每个从机的在线状态、缓存和手动写请求一起复位。 */
    for (i = 0U; i < RS485_SLAVE_COUNT; i++) {
        uint8_t reg_i;
        for (reg_i = 0U; reg_i < MODBUS_REG_SENSOR_COUNT; reg_i++) {
            s_ctx.slave.regs[i][reg_i] = 0U;
        }
        s_ctx.slave.control_target[i] = MODBUS_CONTROL_OFF_VALUE;
        s_ctx.slave.manual_write_pending[i] = 0U;
        s_ctx.slave.manual_write_value[i] = MODBUS_CONTROL_OFF_VALUE;
        s_ctx.slave.online[i] = 1U;
        s_ctx.slave.fail_streak[i] = 0U;
        s_ctx.slave.retry_tick[i] = s_ctx.poll.last_poll_tick;
    }

    memset(s_ctx.txn.tx_buf, 0, sizeof(s_ctx.txn.tx_buf));
    memset(s_ctx.txn.rx_buf, 0, sizeof(s_ctx.txn.rx_buf));

    return 1U;
}

/* RS485 主机任务：非阻塞轮询状态机，带超时、重试、离线管理。 */
/**
 * @brief RS485 Modbus 主机任务主循环
 *
 * 此函数实现非阻塞状态机驱动的 Modbus-RTU 通信：
 * - 轮询所有从机，执行读保持寄存器和写单寄存器操作
 * - 管理从机在线/离线状态，自动恢复离线设备
 * - 处理通信超时、重试和错误恢复
 * - 基于传感器数据自动控制从机状态
 *
 * 状态机流程：
 * IDLE -> TX -> WAIT_TC -> RX -> IDLE (成功) 或 重试/失败处理
 *
 * @note 此函数应在 FreeRTOS 任务中周期性调用，不阻塞主循环
 */
void Task_RS485_Run(void)
{
    uint32_t now;  // 当前时间戳，用来驱动超时和轮询节拍。

    /* 先处理控制台命令，保证手动写请求在下一轮事务前就绪。 */
    Task_RS485_ConsoleProcess();

    now = HAL_GetTick();

    /* UART 实例无效时直接返回，避免对未初始化外设做任何访问。 */
    if (RS485_COMM_UART_HANDLE.Instance == 0) {
        return;
    }

    /* 空闲态只负责按周期启动新事务，不在此处做阻塞等待。 */
    if (s_ctx.txn.comm_state == RS485_COMM_IDLE) {
        if ((now - s_ctx.poll.last_poll_tick) < RS485_POLL_INTERVAL_MS) {
            return;
        }

        RS485_TryStartTransaction(now);
        return;
    }

    /* 当前事务若超时，则走统一失败路径。 */
    if (RS485_SchedIsTimeout(now, s_ctx.txn.state_deadline_tick) != 0U) {
        RS485_HandleTransactionFailure(now, RS485_ERR_TIMEOUT);
        return;
    }

    /*
     * 发送阶段在一次任务调用内尽可能完成整帧发送。
     *
     * 迁移到 FreeRTOS 后，任务按固定周期运行；如果仍然每次只发 1 字节，
     * 会在超时窗口内无法发完整帧，导致从机看到请求但主机状态机持续失败。
     * 这里改为“有超时保护的整帧推进”，确保调度周期变慢时链路仍可闭环。
     */
    if (s_ctx.txn.comm_state == RS485_COMM_TX) {
        while (s_ctx.txn.tx_idx < s_ctx.txn.tx_len) {
            now = HAL_GetTick();
            if (RS485_SchedIsTimeout(now, s_ctx.txn.state_deadline_tick) != 0U) {
                RS485_HandleTransactionFailure(now, RS485_ERR_TIMEOUT);
                return;
            }

            if (__HAL_UART_GET_FLAG(&RS485_COMM_UART_HANDLE, UART_FLAG_TXE) != RESET) {
                RS485_COMM_UART_HANDLE.Instance->DR = s_ctx.txn.tx_buf[s_ctx.txn.tx_idx];
                s_ctx.txn.tx_idx++;
            }
        }

        now = HAL_GetTick();
        s_ctx.txn.state_deadline_tick = now + RS485_RX_TIMEOUT_MS;
        s_ctx.txn.comm_state = RS485_COMM_WAIT_TC;
    }

    /*
     * 等待移位寄存器真正发完，再切入接收阶段。
     * 这里同样使用有界等待，防止外设异常时卡住任务。
     */
    if (s_ctx.txn.comm_state == RS485_COMM_WAIT_TC) {
        while (__HAL_UART_GET_FLAG(&RS485_COMM_UART_HANDLE, UART_FLAG_TC) == RESET) {
            now = HAL_GetTick();
            if (RS485_SchedIsTimeout(now, s_ctx.txn.state_deadline_tick) != 0U) {
                RS485_HandleTransactionFailure(now, RS485_ERR_TIMEOUT);
                return;
            }
        }

        now = HAL_GetTick();
        s_ctx.txn.state_deadline_tick = now + RS485_RX_TIMEOUT_MS;
        s_ctx.txn.comm_state = RS485_COMM_RX;
    }

    /*
     * 接收阶段在一次调用内尽量收齐响应窗口。
     *
     * 同样是为适配 FreeRTOS 周期调度：如果每个周期只读 1 字节，
     * 在 115200 波特率下会严重丢字节并长期保持全 0 数据。
     */
    if (s_ctx.txn.comm_state == RS485_COMM_RX) {
        while (s_ctx.txn.rx_idx < sizeof(s_ctx.txn.rx_buf)) {
            now = HAL_GetTick();
            if (RS485_SchedIsTimeout(now, s_ctx.txn.state_deadline_tick) != 0U) {
                RS485_HandleTransactionFailure(now, RS485_ERR_TIMEOUT);
                return;
            }

            if (__HAL_UART_GET_FLAG(&RS485_COMM_UART_HANDLE, UART_FLAG_RXNE) != RESET) {
                s_ctx.txn.rx_buf[s_ctx.txn.rx_idx] = (uint8_t)(RS485_COMM_UART_HANDLE.Instance->DR & 0x00FFU);
                s_ctx.txn.rx_idx++;

                /* 收到新字节后刷新接收超时窗口，兼容从机响应字节间微小抖动。 */
                now = HAL_GetTick();
                s_ctx.txn.state_deadline_tick = now + RS485_RX_TIMEOUT_MS;

                /* 每次读到新字节后立即尝试解析，命中即结束事务。 */
                if (RS485_TryHandleRxWindow(now) != 0U) {
                    return;
                }
            }
        }

        /*
         * 每轮都尝试一次滑窗匹配：
         * - 命中合法响应会在内部走成功路径并结束事务；
         * - 写满窗口仍未命中则走失败路径；
         * - 否则继续等待后续字节直到超时。
         */
        now = HAL_GetTick();
        if (RS485_TryHandleRxWindow(now) != 0U) {
            return;
        }

        return;
    }

    /* 异常状态自恢复，避免状态机因意外值卡死。 */
    RS485_EndTransaction();
}

/**
 * @brief 打印诊断信息到调试串口
 *
 * 输出包括：
 * - 通信统计：成功/失败次数
 * - 从机状态：在线/离线、连续失败计数
 * - 最近错误历史：循环缓冲区中的错误码
 */
void Task_RS485_PrintDiag(void)
{
    char buf[256];  // 诊断输出缓冲区，扩展以容纳两个从机。
    uint8_t last_err_idx;
    uint8_t last_err;
    uint16_t s1_adc, s1_threshold, s1_lux, s1_relay;
    int16_t s2_accel_x, s2_accel_y, s2_accel_z;
    uint16_t s2_servo;
    uint8_t s2_servo_valid;
    int len;  // 字符串长度
    uint32_t lock_state;
    uint32_t tx_lock_state;

    lock_state = RS485_LockEnter();

    /* 环形缓冲回看上一次错误，便于稳定输出最近故障。 */
    if (s_ctx.diag.error_history_index == 0U)
    {
        last_err_idx = (uint8_t)(RS485_ERROR_HISTORY_SIZE - 1U);
    }
    else
    {
        last_err_idx = (uint8_t)(s_ctx.diag.error_history_index - 1U);
    }
    last_err = (uint8_t)s_ctx.diag.error_history[last_err_idx];

    // 从机1数据
    s1_adc = s_ctx.slave.regs[0][0];
    s1_threshold = s_ctx.slave.regs[0][1];
    s1_lux = s_ctx.slave.regs[0][2];
    s1_relay = s_ctx.slave.regs[0][3];

    // 从机2数据
    // 从机2加速度寄存器是 int16 原始值，这里按有符号数解释便于观测正负方向。
    s2_accel_x = (int16_t)s_ctx.slave.regs[1][0];
    s2_accel_y = (int16_t)s_ctx.slave.regs[1][1];
    s2_accel_z = (int16_t)s_ctx.slave.regs[1][2];
    s2_servo = s_ctx.slave.regs[1][3];
    // 舵机角度有效范围 0~180，超范围可用于快速识别映射/协议异常。
    s2_servo_valid = (s2_servo <= 180U) ? 1U : 0U;
    RS485_LockExit(lock_state);

    /* 输出两个从机的健康状态和寄存器快照。 */
    len = snprintf(buf,
                   sizeof(buf),
                   "M S1_ON=%u ADC=%u TH=%u LUX=%u RELAY=%u S2_ON=%u AX=%d AY=%d AZ=%d SERVO=%u SERVO_OK=%u OK=%lu FAIL=%lu E=%u\r\n",
                  (unsigned int)s_ctx.slave.online[0],
                  (unsigned int)s1_adc,
                  (unsigned int)s1_threshold,
                  (unsigned int)s1_lux,
                  (unsigned int)s1_relay,
                  (unsigned int)s_ctx.slave.online[1],
                  (int)s2_accel_x,
                  (int)s2_accel_y,
                  (int)s2_accel_z,
                  (unsigned int)s2_servo,
                  (unsigned int)s2_servo_valid,
                  (unsigned long)s_ctx.diag.comm_ok_cnt,
                  (unsigned long)s_ctx.diag.comm_fail_cnt,
                  (unsigned int)last_err);
    if (len > 0)
    {
        uint16_t sent = 0U;
        uint16_t total_len = (uint16_t)len;
        uint32_t start_tick = HAL_GetTick();

        /* 诊断输出和控制台应答共用 USART2，所以这里先获取发送互斥量。 */
        tx_lock_state = Uart2_TxLockEnter();
        if (tx_lock_state != 0U)
        {
            return;
        }

        /* 诊断串口只占用有限发送预算，避免打印路径阻塞通信状态机。 */
        while (sent < total_len) {
            if (__HAL_UART_GET_FLAG(&RS485_DIAG_UART_HANDLE, UART_FLAG_TXE) != RESET) {
                RS485_DIAG_UART_HANDLE.Instance->DR = (uint16_t)((uint8_t)buf[sent]);
                sent++;
                start_tick = HAL_GetTick();
                continue;
            }

            if ((HAL_GetTick() - start_tick) > RS485_DIAG_TX_BUDGET_MS) {
                break;
            }
        }

        Uart2_TxLockExit(tx_lock_state);
    }
}

uint16_t Task_RS485_GetSlaveRegister(uint8_t slave_idx, uint8_t reg_idx)
{
    uint16_t reg_value;
    uint32_t lock_state;

    if ((slave_idx >= RS485_SLAVE_COUNT) || (reg_idx >= MODBUS_REG_SENSOR_COUNT)) {
        return 0U;
    }

    lock_state = RS485_LockEnter();
    reg_value = s_ctx.slave.regs[slave_idx][reg_idx];
    RS485_LockExit(lock_state);

    return reg_value;
}

uint8_t Task_RS485_GetSlaveOnline(uint8_t slave_idx)
{
    uint8_t online_state;
    uint32_t lock_state;

    if (slave_idx >= RS485_SLAVE_COUNT) {
        return 0U;
    }

    lock_state = RS485_LockEnter();
    online_state = s_ctx.slave.online[slave_idx];
    RS485_LockExit(lock_state);

    return online_state;
}

uint8_t Task_RS485_GetManualWritePending(uint8_t slave_idx)
{
    uint8_t pending_state;
    uint32_t lock_state;

    if (slave_idx >= RS485_SLAVE_COUNT) {
        return 0U;
    }

    lock_state = RS485_LockEnter();
    pending_state = s_ctx.slave.manual_write_pending[slave_idx];
    RS485_LockExit(lock_state);

    return pending_state;
}

void Task_RS485_RequestManualWrite(uint8_t slave_idx, uint16_t control_value)
{
    uint32_t lock_state;

    /*
     * 这个接口同时承载从机1阈值写和从机2舵机角度写，值域按从机索引区分校验。
     * 这里仅负责“合法请求入队”，不直接触发串口发送，避免控制台线程抢占通信时序。
     */
    if ((slave_idx >= RS485_SLAVE_COUNT) ||
        (RS485_IsManualWriteValueValid(slave_idx, control_value) == 0U)) {
        return;
    }

    /* 这里只入队，不直接发送，保持写事务仍由主状态机统一调度。 */
    lock_state = RS485_LockEnter();
    s_ctx.slave.manual_write_value[slave_idx] = control_value;
    s_ctx.slave.manual_write_pending[slave_idx] = 1U;
    RS485_LockExit(lock_state);
}
