; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:stm32f103c8]
; 1. 开发平台与芯片配置
platform = ststm32        ; 指定开发平台为 STM32
board = genericSTM32F103C8 ; 对应芯片型号：STM32F103C8T6 (通用型)
framework = stm32cube    ; 使用 STM32Cube HAL 库开发
upload_protocol = stlink    ; 烧录工具选择：ST-Link
debug_tool = stlink

build_type = debug
; 2. 编译构建参数 (编译器传入参数)
build_flags =
  -DSTM32F103xB           ; 定义芯片型号宏 (128KB Flash 版本)
  -DUSE_HAL_DRIVER        ; 启用 STM32 HAL 驱动库
  -ICore/Inc              ; 添加头文件路径：核心层 (HAL/启动文件)
  -IApp/Inc               ; 添加头文件路径：应用层 (自定义任务/逻辑)

; 3. 源文件过滤 (指定编译哪些目录的代码)
; 只编译 Core 层 (系统初始化) 和 App 层 (业务逻辑)，避免冗余编译和扫描
build_src_filter = +<Core/Src/*.c> +<Core/Src/**/*.c> +<App/Src/*.c> +<App/Src/**/*.c> -<Drivers/**> -<include/**> -<lib/**> -<src/**> -<test/**>

; 4. 库依赖声明
; 指定本地 HAL 驱动库路径 (建议相对路径以适配多环境)
lib_deps =
    Drivers\STM32F1xx_HAL_Driver

; 5. 项目根目录
; 指定源码根目录为当前目录 (.), 适配 CubeMX 生成的目录结构
[platformio]
src_dir = .