/**
 * @file app_config.h
 * @brief 应用层配置常量定义
 *
 * 此文件集中定义从机应用层常量，包括 Modbus 协议参数、RS485 驱动缓冲区大小、
 * 帧结束判定阈值、光照控制参数和自检模式开关。
 *
 * 主要内容：
 * - Modbus 地址、功能码与寄存器常量
 * - RS485 接收发送缓冲区与帧结束阈值
 * - 光照转换与继电器控制参数
 * - 应用自检模式开关
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

// Modbus 从机地址：本设备在总线上的唯一标识，范围 1-247。
#define MODBUS_SLAVE_ADDRESS                    (0x01U)
// Modbus 功能码：读保持寄存器，请求读取连续的寄存器值。
#define MODBUS_FUNC_READ_HOLDING                (0x03U)
// Modbus 功能码：写单个寄存器，请求修改一个寄存器的值。
#define MODBUS_FUNC_WRITE_SINGLE                (0x06U)

// Modbus 应用数据单元最大长度（字节），包括地址、功能码、数据、CRC。
#define MODBUS_MAX_ADU_LENGTH                   (256U)
// UART RX DMA 环形缓冲区大小（字节），用于缓存接收数据。
#define MODBUS_RX_DMA_BUFFER_SIZE               (256U)
// UART TX DMA 发送缓冲区大小（字节），用于缓存待发送数据。
#define MODBUS_TX_BUFFER_SIZE                   (256U)

// Modbus 请求帧最小长度（字节），包括地址、功能码、数据、CRC。
#define MODBUS_MIN_REQUEST_LENGTH               (8U)
// Modbus 寄存器地址：ADC 原始值（只读，范围 0-4095）。
#define MODBUS_REG_ADDR_ADC_RAW                 (0x0000U)
// Modbus 寄存器地址：光照阈值（可读写，默认 500，单位 lux）。
#define MODBUS_REG_ADDR_LIGHT_THRESHOLD         (0x0001U)
// Modbus 寄存器地址：转换后光照值（只读，单位 lux）。
#define MODBUS_REG_ADDR_LIGHT_LUX               (0x0002U)
// Modbus 寄存器地址：继电器状态（只读，0=关，1=开）。
#define MODBUS_REG_ADDR_RELAY_STATE             (0x0003U)
// Modbus 总寄存器数量（地址 0x0000 到 0x0003）。
#define MODBUS_REGISTER_COUNT                   (4U)

// Modbus 帧结束判定：3.5 字符间隔的 tick 计数（基于 TIM2 304us 周期）。
#define MODBUS_FRAME_END_TICKS                  (1U)

// RS485 发送使能前延时（毫秒），确保总线稳定后拉高 DE。
#define RS485_TX_ENABLE_DELAY_MS                (1U)
// RS485 发送完成后延时（毫秒），确保数据发送完毕后再拉低 DE。
#define RS485_TX_DISABLE_DELAY_MS               (1U)

// 光照转换公式分子（mV），对应 ADC 满量程电压 3.3V。
#define LIGHT_LUX_SCALE_NUMERATOR               (3300U)
// ADC 最大值（12 位分辨率）。
#define LIGHT_ADC_MAX_VALUE                     (4095U)
// 光敏传感器缩放系数（无单位，校准用）。
#define LIGHT_SENSOR_SCALE                      (1000U)
// 光照阈值默认值（单位 lux，低于此值开继电器）。
#define LIGHT_THRESHOLD_DEFAULT                 (1600U)
// 光照阈值下限（单位 lux）。
#define LIGHT_THRESHOLD_MIN                     (0U)
// 光照阈值上限（单位 lux），按当前换算公式理论最大值限定。
#define LIGHT_THRESHOLD_MAX                     ((LIGHT_LUX_SCALE_NUMERATOR * LIGHT_SENSOR_SCALE) / 1000U)
// 继电器回差宽度（单位 lux），用于避免阈值附近抖动。
#define LIGHT_RELAY_HYSTERESIS_LUX              (80U)

// 自检模式：1=暂停 RS485 从机通信，仅输出链路诊断信息。
// 量产/联调默认关闭（0），恢复正常从机通信路径。
#define APP_SELF_TEST_USE_USART1_DEBUG          (0U)

#endif
