/**
 * @file light_control.h
 * @brief 光照控制模块接口声明
 *
 * 此文件声明光照控制模块接口，负责 ADC 样本处理、lux 计算、阈值管理与继电器
 * 状态查询，为 Modbus 寄存器映射提供数据来源。
 *
 * 主要内容：
 * - 光照控制初始化与采样输入接口
 * - lux/阈值/继电器状态读取接口
 * - 阈值设置与合法性校验接口
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#ifndef LIGHT_CONTROL_H
#define LIGHT_CONTROL_H

#include <stdbool.h>
#include <stdint.h>

// 光照控制模块初始化：在 app_main_init() 中调用，复位状态和 GPIO。
void light_control_init(void);

// ADC 采样完成回调：在 ADC 中断中调用，更新 lux 并控制继电器。
// 参数：adc_raw - ADC 原始值（0-4095）。
void light_control_on_adc_sample(uint16_t adc_raw);

// 获取最新 ADC 原始值：供 Modbus 读取寄存器 0x0000。
// 返回：ADC 值（0-4095）。
uint16_t light_control_get_adc_raw(void);

// 获取最新 lux 值：供 Modbus 读取寄存器 0x0002。
// 返回：lux 值（单位 lux）。
uint16_t light_control_get_lux(void);

// 获取当前光照阈值：供 Modbus 读取寄存器 0x0001。
// 返回：阈值（单位 lux）。
uint16_t light_control_get_threshold(void);

// 设置光照阈值：供 Modbus 写寄存器 0x0001。
// 参数：threshold - 新阈值（单位 lux）。
void light_control_set_threshold(uint16_t threshold);

// 校验阈值是否在允许范围内。
// 参数：threshold - 待校验阈值（单位 lux）。
// 返回：true=合法；false=越界。
bool light_control_is_threshold_valid(uint16_t threshold);

// 获取继电器状态：供 Modbus 读取寄存器 0x0003。
// 返回：0=关，1=开。
uint16_t light_control_get_relay_state(void);

#endif
