/**
 * @file task_app.h
 * @brief 应用主流程接口声明
 *
 * 此文件声明应用层主流程接口，包括初始化、主循环轮询和各类中断回调入口，
 * 用于把底层外设事件统一转发到业务模块。
 *
 * 主要内容：
 * - 应用初始化与主循环接口
 * - USART/UART/TIM/ADC 回调接口
 * - 中断到应用层的统一入口声明
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#ifndef APP_MAIN_H
#define APP_MAIN_H

#include "adc.h"
#include "tim.h"
#include "usart.h"

// 应用层初始化：在 main() 中调用一次，启动所有外设和模块。
void app_main_init(void);

// 应用层主循环：在 while(1) 中调用，处理 Modbus 协议和 RS485 状态机。
void app_main_poll(void);

// USART IDLE 中断回调：在 stm32f1xx_it.c 中调用，通知串口空闲事件。
void app_main_on_usart_idle_irq(void);

// UART 发送完成中断回调：在 stm32f1xx_it.c 中调用，通知 DMA 发送完毕。
// 参数：huart - UART 句柄。
void app_main_on_uart_tx_cplt_irq(UART_HandleTypeDef *huart);

// TIM2 更新事件中断回调：在 stm32f1xx_it.c 中调用，预留诊断用。
void app_main_on_tim2_irq_tick(void);

// TIM2 输出比较事件中断回调：在 stm32f1xx_it.c 中调用，处理 CH1 帧结束 tick。
// 参数：htim - TIM 句柄。
void app_main_on_tim2_oc_elapsed_irq(TIM_HandleTypeDef *htim);

// ADC 转换完成中断回调：在 main.c 中调用，处理采样数据。
// 参数：hadc - ADC 句柄。
void app_main_on_adc_conv_cplt_irq(ADC_HandleTypeDef *hadc);

#endif
