/**
 * @file light_control.c
 * @brief 光照控制模块实现
 *
 * 此文件实现光照控制算法，处理 ADC 原始采样到 lux 转换、阈值回差控制和继电器
 * 输出驱动，并向 Modbus 协议层提供状态读取接口。
 *
 * 主要内容：
 * - ADC 到 lux 的转换实现
 * - 继电器回差控制策略实现
 * - 阈值管理与状态读取接口实现
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#include "light_control.h"

#include "app_config.h"
#include "main.h"

// 最新 ADC 原始值（0~4095）。
static volatile uint16_t s_adc_raw = 0U;
// 最新 lux 结果。
static volatile uint16_t s_lux = 0U;
// 光照阈值寄存器（可写）。
static volatile uint16_t s_light_threshold = LIGHT_THRESHOLD_DEFAULT;
// 继电器状态：0 关，1 开。
static volatile uint16_t s_relay_state = 0U;

// 继电器使能电平：按当前硬件采用低电平吸合。
#define RELAY_CTRL_ACTIVE_LEVEL    GPIO_PIN_RESET
// 继电器关闭电平：与使能电平相反。
#define RELAY_CTRL_INACTIVE_LEVEL  GPIO_PIN_SET

// 将逻辑状态映射到物理继电器引脚电平。
static void light_control_apply_relay_output(uint16_t relay_state)
{
    HAL_GPIO_WritePin(RELAY_CTRL_GPIO_Port,
                      RELAY_CTRL_Pin,
                      (relay_state != 0U) ? RELAY_CTRL_ACTIVE_LEVEL : RELAY_CTRL_INACTIVE_LEVEL);
}

// ADC 转 lux：lux = (3.3 - adc*3.3/4095) * 系数。
static uint16_t light_control_adc_to_lux(uint16_t adc_raw)
{
    // adc 对应电压（mV），范围 0~3300。
    uint32_t scaled_mv = ((uint32_t)adc_raw * LIGHT_LUX_SCALE_NUMERATOR) / LIGHT_ADC_MAX_VALUE;
    // 按公式做反向电压。
    uint32_t inverted_mv = LIGHT_LUX_SCALE_NUMERATOR - scaled_mv;
    // 乘以传感器缩放系数。
    uint32_t lux = inverted_mv * LIGHT_SENSOR_SCALE;

    // mV 转换回整数 lux。
    lux = lux / 1000U;
    // 防止超出 16 位输出范围。
    if (lux > 0xFFFFU)
    {
        lux = 0xFFFFU;
    }

    // 返回 16 位 lux。
    return (uint16_t)lux;
}

void light_control_init(void)
{
    // 复位采样值。
    s_adc_raw = 0U;
    // 复位 lux。
    s_lux = 0U;
    // 恢复默认阈值。
    s_light_threshold = LIGHT_THRESHOLD_DEFAULT;
    // 复位继电器状态。
    s_relay_state = 0U;

    // 上电安全默认：继电器关闭。
    light_control_apply_relay_output(0U);
}

void light_control_on_adc_sample(uint16_t adc_raw)
{
    // 继电器目标状态。
    uint16_t relay_state;
    // 开灯阈值（带回差下沿）。
    uint16_t threshold_on;
    // 关灯阈值（带回差上沿）。
    uint16_t threshold_off;
    // 上沿扩展的 32 位临时值，避免 16 位加法溢出。
    uint32_t threshold_off_u32;

    // 更新原始 ADC。
    s_adc_raw = adc_raw;
    // 更新 lux。
    s_lux = light_control_adc_to_lux(adc_raw);

    // 计算回差窗口：阈值下沿用于开灯，上沿用于关灯。
    threshold_on = (s_light_threshold > LIGHT_RELAY_HYSTERESIS_LUX)
                   ? (uint16_t)(s_light_threshold - LIGHT_RELAY_HYSTERESIS_LUX)
                   : 0U;
    threshold_off_u32 = (uint32_t)s_light_threshold + (uint32_t)LIGHT_RELAY_HYSTERESIS_LUX;
    threshold_off = (threshold_off_u32 > 0xFFFFU) ? 0xFFFFU : (uint16_t)threshold_off_u32;

    // 先继承上一时刻状态，再按回差阈值决定是否切换。
    relay_state = s_relay_state;

    // 当前为关，仅当亮度低于下沿时才开灯。
    if ((relay_state == 0U) && (s_lux <= threshold_on))
    {
        relay_state = 1U;
    }
    // 当前为开，仅当亮度高于上沿时才关灯。
    else if ((relay_state != 0U) && (s_lux >= threshold_off))
    {
        relay_state = 0U;
    }

    // 保存状态供寄存器读取。
    s_relay_state = relay_state;

    // 输出到继电器 GPIO。
    light_control_apply_relay_output(relay_state);
}

uint16_t light_control_get_adc_raw(void)
{
    // 返回最新 ADC 原始值。
    return s_adc_raw;
}

uint16_t light_control_get_lux(void)
{
    // 返回最新 lux。
    return s_lux;
}

uint16_t light_control_get_threshold(void)
{
    // 返回当前阈值。
    return s_light_threshold;
}

void light_control_set_threshold(uint16_t threshold)
{
    // 入参高于上限时按上限钳位。
    if (threshold > LIGHT_THRESHOLD_MAX)
    {
        threshold = LIGHT_THRESHOLD_MAX;
    }

    // 入参低于下限时按下限钳位。
    if (threshold < LIGHT_THRESHOLD_MIN)
    {
        threshold = LIGHT_THRESHOLD_MIN;
    }

    // 更新阈值。
    s_light_threshold = threshold;
}

bool light_control_is_threshold_valid(uint16_t threshold)
{
    // 越界返回 false。
    if ((threshold < LIGHT_THRESHOLD_MIN) || (threshold > LIGHT_THRESHOLD_MAX))
    {
        return false;
    }

    // 合法范围返回 true。
    return true;
}

uint16_t light_control_get_relay_state(void)
{
    // 返回继电器状态。
    return s_relay_state;
}
