/**
 * @file rs485_driver.c
 * @brief RS485 驱动统一实现
 *
 * 此文件统一实现 RS485 驱动收发链路，包括 RX DMA 环形接收、IDLE + 静默 tick
 * 判帧结束、整帧提取，以及 TX DMA 异步发送与完成回调处理。
 *
 * 主要内容：
 * - 驱动内部上下文与状态机定义
 * - RX 链路（DMA/IDLE/静默判帧/取帧）
 * - TX 链路（DMA 发送/发送完成回调）
 * - 对外 API 与中断入口
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#include "rs485_driver.h"

#include <string.h>

#include "app_config.h"

// ==================== 私有类型与上下文 ====================

// RS485 发送状态机。
typedef enum
{
    // 空闲态：可发可收。
    RS485_TX_STATE_IDLE = 0,
    // DMA 正在发送。
    RS485_TX_STATE_DMA_BUSY
} Rs485TxState_t;

// RS485 驱动内部共享上下文，集中保存收发链路状态。
typedef struct
{
    // 串口句柄，由上层初始化时注入。
    UART_HandleTypeDef *huart;

    // UART RX DMA 环形缓冲区。
    uint8_t rx_dma_buffer[MODBUS_RX_DMA_BUFFER_SIZE];
    // UART TX DMA 线性发送缓冲区。
    uint8_t tx_dma_buffer[MODBUS_TX_BUFFER_SIZE];

    // 环形缓冲区读指针：指向尚未交付上层的起始位置。
    volatile uint16_t rx_read_pos;
    // 记录 IDLE 中断到来时 DMA 当前写入位置。
    volatile uint16_t rx_idle_pos;
    // 标记已观测到一次串口空闲事件。
    volatile uint8_t rx_idle_seen;
    // 标记一帧数据已经可以被主循环提取。
    volatile uint8_t rx_frame_ready;
    // 当前待提取帧长度。
    volatile uint16_t rx_frame_length;
    // 空闲计数 tick，用于 3.5 字符间隔判定。
    volatile uint16_t silence_ticks;

    // 发送状态机当前状态。
    volatile Rs485TxState_t tx_state;
    // 本次 DMA 发送长度。
    volatile uint16_t tx_length;
} Rs485DriverContext_t;

// RS485 驱动内部唯一上下文实例。
static Rs485DriverContext_t s_driver_ctx = {0};

// ==================== RX 链路私有实现 ====================

// 计算环形缓冲区 from 到 to 的距离。
static uint16_t rs485_distance_in_ring(uint16_t from, uint16_t to)
{
    // 未回卷，直接相减。
    if (to >= from)
    {
        return (uint16_t)(to - from);
    }

    // 已回卷，尾段长度加头段长度。
    return (uint16_t)((MODBUS_RX_DMA_BUFFER_SIZE - from) + to);
}

// 复位接收链路上下文。
static void rs485_driver_rx_reset(void)
{
    s_driver_ctx.rx_read_pos = 0U;
    s_driver_ctx.rx_idle_pos = 0U;
    s_driver_ctx.rx_idle_seen = 0U;
    s_driver_ctx.rx_frame_ready = 0U;
    s_driver_ctx.rx_frame_length = 0U;
    s_driver_ctx.silence_ticks = 0U;
}

// 启动 RX DMA 与 IDLE 中断。
static void rs485_driver_rx_start(void)
{
    if (s_driver_ctx.huart == NULL)
    {
        return;
    }

    if (HAL_UART_Receive_DMA(s_driver_ctx.huart,
                             s_driver_ctx.rx_dma_buffer,
                             MODBUS_RX_DMA_BUFFER_SIZE) != HAL_OK)
    {
        // 启动失败时保持静默，等待上层重试策略。
        return;
    }

    // 关闭半传输中断，降低无效中断负担。
    __HAL_DMA_DISABLE_IT(s_driver_ctx.huart->hdmarx, DMA_IT_HT);
    // 使能 IDLE 中断，通过串口空闲来感知“可能帧尾”。
    __HAL_UART_ENABLE_IT(s_driver_ctx.huart, UART_IT_IDLE);
}

// 处理 USART IDLE 中断，记录候选帧尾。
static void rs485_driver_rx_on_usart_idle_irq(void)
{
    uint16_t current_pos;

    if (s_driver_ctx.huart == NULL)
    {
        return;
    }

    if (__HAL_UART_GET_FLAG(s_driver_ctx.huart, UART_FLAG_IDLE) == RESET)
    {
        return;
    }

    if (__HAL_UART_GET_IT_SOURCE(s_driver_ctx.huart, UART_IT_IDLE) == RESET)
    {
        return;
    }

    // 清除 IDLE 标志，避免重复进入。
    __HAL_UART_CLEAR_IDLEFLAG(s_driver_ctx.huart);

    // 通过剩余计数换算 DMA 当前写入位置。
    current_pos = (uint16_t)(MODBUS_RX_DMA_BUFFER_SIZE -
                             __HAL_DMA_GET_COUNTER(s_driver_ctx.huart->hdmarx));
    if (current_pos >= MODBUS_RX_DMA_BUFFER_SIZE)
    {
        current_pos = 0U;
    }

    // 保存空闲时刻写指针并开始 silence 计时。
    s_driver_ctx.rx_idle_pos = current_pos;
    s_driver_ctx.rx_idle_seen = 1U;
    s_driver_ctx.silence_ticks = 0U;
}

// 处理静默 tick，判定是否达到 3.5 字符间隔。
static void rs485_driver_rx_on_silence_tick_irq(void)
{
    uint16_t frame_length;

    if ((s_driver_ctx.rx_idle_seen == 0U) || (s_driver_ctx.rx_frame_ready != 0U))
    {
        return;
    }

    s_driver_ctx.silence_ticks++;
    if (s_driver_ctx.silence_ticks < MODBUS_FRAME_END_TICKS)
    {
        return;
    }

    // 达到阈值后，按读指针到 idle 指针计算帧长度。
    frame_length = rs485_distance_in_ring(s_driver_ctx.rx_read_pos, s_driver_ctx.rx_idle_pos);
    if (frame_length == 0U)
    {
        s_driver_ctx.rx_idle_seen = 0U;
        s_driver_ctx.silence_ticks = 0U;
        return;
    }

    s_driver_ctx.rx_frame_length = frame_length;
    s_driver_ctx.rx_frame_ready = 1U;
    s_driver_ctx.rx_idle_seen = 0U;
    s_driver_ctx.silence_ticks = 0U;
}

// 从 DMA 环形缓冲区提取一帧数据。
static bool rs485_driver_rx_fetch_frame(uint8_t *frame,
                                        uint16_t frame_buf_size,
                                        uint16_t *frame_len)
{
    uint16_t i;
    uint16_t length;

    if ((frame == NULL) || (frame_len == NULL))
    {
        return false;
    }

    if (s_driver_ctx.rx_frame_ready == 0U)
    {
        return false;
    }

    length = s_driver_ctx.rx_frame_length;
    if ((length == 0U) || (length > frame_buf_size))
    {
        // 长度异常时丢弃当前帧，读指针追到 idle 位置。
        s_driver_ctx.rx_read_pos = s_driver_ctx.rx_idle_pos;
        s_driver_ctx.rx_frame_ready = 0U;
        s_driver_ctx.rx_frame_length = 0U;
        return false;
    }

    // 从 DMA 环形缓冲区按顺序拷贝整帧。
    for (i = 0U; i < length; i++)
    {
        uint16_t index = (uint16_t)((s_driver_ctx.rx_read_pos + i) % MODBUS_RX_DMA_BUFFER_SIZE);
        frame[i] = s_driver_ctx.rx_dma_buffer[index];
    }

    s_driver_ctx.rx_read_pos = s_driver_ctx.rx_idle_pos;
    s_driver_ctx.rx_frame_ready = 0U;
    s_driver_ctx.rx_frame_length = 0U;

    *frame_len = length;
    return true;
}

// ==================== TX 链路私有实现 ====================

// 复位发送状态机上下文。
static void rs485_driver_tx_reset(void)
{
    s_driver_ctx.tx_state = RS485_TX_STATE_IDLE;
    s_driver_ctx.tx_length = 0U;
}

// 处理 UART DMA 发送完成回调。
static void rs485_driver_tx_on_uart_tx_complete_irq(UART_HandleTypeDef *huart)
{
    if ((s_driver_ctx.huart == NULL) || (huart != s_driver_ctx.huart))
    {
        return;
    }

    // 自动收发模块由硬件完成方向切换，发送完成即可回空闲态。
    s_driver_ctx.tx_state = RS485_TX_STATE_IDLE;
    s_driver_ctx.tx_length = 0U;
}

// 通过 DMA 异步发送一帧数据。
static bool rs485_driver_tx_send(const uint8_t *data, uint16_t length)
{
    if ((s_driver_ctx.huart == NULL) || (data == NULL) || (length == 0U) ||
        (length > MODBUS_TX_BUFFER_SIZE))
    {
        return false;
    }

    if (s_driver_ctx.tx_state != RS485_TX_STATE_IDLE)
    {
        return false;
    }

    memcpy(s_driver_ctx.tx_dma_buffer, data, length);
    s_driver_ctx.tx_length = length;

    if (HAL_UART_Transmit_DMA(s_driver_ctx.huart,
                              s_driver_ctx.tx_dma_buffer,
                              s_driver_ctx.tx_length) != HAL_OK)
    {
        s_driver_ctx.tx_state = RS485_TX_STATE_IDLE;
        s_driver_ctx.tx_length = 0U;
        return false;
    }

    s_driver_ctx.tx_state = RS485_TX_STATE_DMA_BUSY;
    return true;
}

// ==================== 对外 API 实现 ====================

void rs485_driver_init(UART_HandleTypeDef *huart)
{
    // 保存串口句柄并复位收发上下文。
    s_driver_ctx.huart = huart;
    rs485_driver_rx_reset();
    rs485_driver_tx_reset();
}

void rs485_driver_start(void)
{
    rs485_driver_rx_start();
}

void rs485_driver_on_usart_idle_irq(void)
{
    rs485_driver_rx_on_usart_idle_irq();
}

void rs485_driver_on_uart_tx_complete_irq(UART_HandleTypeDef *huart)
{
    rs485_driver_tx_on_uart_tx_complete_irq(huart);
}

void rs485_driver_on_silence_tick_irq(void)
{
    rs485_driver_rx_on_silence_tick_irq();
}

void rs485_driver_poll(void)
{
    // 未初始化时不处理。
    if (s_driver_ctx.huart == NULL)
    {
        return;
    }

    // 自动收发下发送流程由 DMA 回调闭环，无需轮询推进方向控制。
}

bool rs485_driver_fetch_frame(uint8_t *frame, uint16_t frame_buf_size, uint16_t *frame_len)
{
    return rs485_driver_rx_fetch_frame(frame, frame_buf_size, frame_len);
}

bool rs485_driver_send(const uint8_t *data, uint16_t length)
{
    return rs485_driver_tx_send(data, length);
}
