/**
 * @file task_app.c
 * @brief 应用主流程实现
 *
 * 此文件实现从机应用主流程，包括系统初始化顺序、主循环轮询以及外设中断回调
 * 到业务模块的转发逻辑。
 *
 * 主要内容：
 * - 应用初始化与模块启动流程
 * - 主循环协议轮询逻辑
 * - USART/UART/TIM/ADC 中断回调转发
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#include "task_app.h"

#include "app_config.h"
#include "gpio.h"
#include "light_control.h"
#include "rs485_slave.h"
#include "rs485_driver.h"

// ADC DMA 单通道缓存。
static uint16_t s_adc_dma_buffer[1];

void app_main_init(void)
{
    // 继电器默认关闭。
    HAL_GPIO_WritePin(RELAY_CTRL_GPIO_Port, RELAY_CTRL_Pin, GPIO_PIN_RESET);

    // 初始化光照控制上下文。
    light_control_init();

    // 自检模式下不启动 RS485 通信，避免总线链路被诊断代码干扰。
#if (APP_SELF_TEST_USE_USART1_DEBUG == 0U)
    // 初始化 RS485 驱动并启动 DMA 接收。
    rs485_driver_init(&huart1);
    rs485_driver_start();

    // 初始化 Modbus 协议层。
    modbus_slave_init();
#endif

    // ADC 校准，提升采样精度。
    HAL_ADCEx_Calibration_Start(&hadc1);
    // 启动 ADC DMA（由 TIM2 CH2 触发）。
    (void)HAL_ADC_Start_DMA(&hadc1, (uint32_t *)s_adc_dma_buffer, 1U);

    // CH1 比较中断用于 3.5 字符静默计时。
    (void)HAL_TIM_OC_Start_IT(&htim2, TIM_CHANNEL_1);
    // CH2 比较中断与 ADC 触发一起启动，便于诊断触发链路。
    (void)HAL_TIM_OC_Start_IT(&htim2, TIM_CHANNEL_2);
    // 启动 TIM2 基本定时中断。
    (void)HAL_TIM_Base_Start_IT(&htim2);
}

void app_main_poll(void)
{
#if (APP_SELF_TEST_USE_USART1_DEBUG == 0U)
    // 主循环中仅做轻量轮询，不在中断执行重处理。
    modbus_slave_poll();
#endif

}

void app_main_on_usart_idle_irq(void)
{
    // USART IDLE 中断：记录帧候选尾。
    modbus_slave_on_usart_idle_irq();
}

void app_main_on_uart_tx_cplt_irq(UART_HandleTypeDef *huart)
{
    // UART DMA 发送完成中断：通知协议层完成发送收尾。
    modbus_slave_on_uart_tx_complete_irq(huart);
}

void app_main_on_tim2_irq_tick(void)
{
    // 预留：TIM2 更新事件处理。
}

void app_main_on_tim2_oc_elapsed_irq(TIM_HandleTypeDef *htim)
{
    // 空指针或非 TIM2 直接返回。
    if ((htim == NULL) || (htim->Instance != TIM2))
    {
        return;
    }

    // 仅 CH1 事件用于 Modbus 帧结束静默计数。
    if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_1)
    {
        modbus_slave_on_silence_tick_irq();
        return;
    }

    // CH2 事件预留。
}

void app_main_on_adc_conv_cplt_irq(ADC_HandleTypeDef *hadc)
{
    // 仅处理 ADC1 转换完成回调。
    if ((hadc == NULL) || (hadc->Instance != ADC1))
    {
        return;
    }

    // 将最新样本交给光照控制模块。
    light_control_on_adc_sample(s_adc_dma_buffer[0]);
}
