/**
 * @file app_config.h
 * @brief 应用层配置常量定义
 *
 * 此文件集中定义从机应用层常量，包括 Modbus 协议参数、RS485 驱动缓冲区大小、
 * MPU6050 采样参数、舵机控制参数以及自检模式开关。
 *
 * 主要内容：
 * - Modbus 地址、功能码与寄存器常量
 * - RS485 接收发送缓冲区与帧结束阈值
 * - MPU6050 采样与寄存器映射参数
 * - SG90 舵机角度与 PWM 参数
 * - 应用自检模式开关
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

// Modbus 从机地址：本设备在总线上的唯一标识，范围 1-247。
#define MODBUS_SLAVE_ADDRESS                    (0x02U)
// Modbus 功能码：读保持寄存器，请求读取连续的寄存器值。
#define MODBUS_FUNC_READ_HOLDING                (0x03U)
// Modbus 功能码：写单个寄存器，请求修改一个寄存器的值。
#define MODBUS_FUNC_WRITE_SINGLE                (0x06U)

// Modbus 应用数据单元最大长度（字节），包括地址、功能码、数据、CRC。
#define MODBUS_MAX_ADU_LENGTH                   (256U)
// UART RX DMA 环形缓冲区大小（字节），用于缓存接收数据。
#define MODBUS_RX_DMA_BUFFER_SIZE               (256U)
// UART TX DMA 发送缓冲区大小（字节），用于缓存待发送数据。
#define MODBUS_TX_BUFFER_SIZE                   (256U)

// Modbus 请求帧最小长度（字节），包括地址、功能码、数据、CRC。
#define MODBUS_MIN_REQUEST_LENGTH               (8U)
// Modbus 寄存器地址：MPU6050 加速度 X 轴原始值（只读，int16 映射为 uint16）。
#define MODBUS_REG_ADDR_ACCEL_X_RAW             (0x0000U)
// Modbus 寄存器地址：MPU6050 加速度 Y 轴原始值（只读，int16 映射为 uint16）。
#define MODBUS_REG_ADDR_ACCEL_Y_RAW             (0x0001U)
// Modbus 寄存器地址：MPU6050 加速度 Z 轴原始值（只读，int16 映射为 uint16）。
#define MODBUS_REG_ADDR_ACCEL_Z_RAW             (0x0002U)
// Modbus 寄存器地址：舵机目标角度（读写，单位度，范围 0-180）。
#define MODBUS_REG_ADDR_SERVO_ANGLE             (0x0003U)
// Modbus 总寄存器数量（地址 0x0000 到 0x0003）。
#define MODBUS_REGISTER_COUNT                   (4U)

// Modbus 帧结束判定：USART IDLE 记录候选帧尾后，TIM2_CH1 通过 tick 计数完成收敛。
#define MODBUS_FRAME_END_TICKS                  (1U)

// RS485 发送使能前延时（毫秒），确保总线稳定后拉高 DE。
#define RS485_TX_ENABLE_DELAY_MS                (1U)
// RS485 发送完成后延时（毫秒），确保数据发送完毕后再拉低 DE。
#define RS485_TX_DISABLE_DELAY_MS               (1U)

// MPU6050 I2C 7-bit 地址（HAL 使用左移 1 位后的 8-bit 地址）。
#define MPU6050_I2C_ADDR                        (0x68U << 1)
// MPU6050 PWR_MGMT_1 寄存器地址。
#define MPU6050_REG_PWR_MGMT_1                  (0x6BU)
// MPU6050 WHO_AM_I 寄存器地址。
#define MPU6050_REG_WHO_AM_I                    (0x75U)
// MPU6050 加速度起始寄存器 ACCEL_XOUT_H。
#define MPU6050_REG_ACCEL_XOUT_H                (0x3BU)
// 唤醒配置值：清除睡眠位。
#define MPU6050_WAKEUP_VALUE                    (0x00U)
// MPU6050 I2C 读写超时（毫秒）。
#define MPU6050_I2C_TIMEOUT_MS                  (20U)
// MPU6050 采样轮询间隔（毫秒）。
#define MPU6050_POLL_INTERVAL_MS                (20U)

// SG90 舵机角度下限（度）。
#define SERVO_ANGLE_MIN                         (0U)
// SG90 舵机角度上限（度）。
#define SERVO_ANGLE_MAX                         (180U)
// SG90 舵机默认角度（度）。
#define SERVO_ANGLE_DEFAULT                     (0U)
// SG90 对应最小脉宽（微秒）。
#define SERVO_PULSE_MIN_US                      (500U)
// SG90 对应最大脉宽（微秒）。
#define SERVO_PULSE_MAX_US                      (2500U)
// SG90 PWM 周期（微秒，20ms 对应 50Hz）。
#define SERVO_PWM_PERIOD_US                     (20000U)

// USART2 临时诊断开关：1=使能从机2独立测试打印，0=关闭。
#define APP_USART2_DIAG_ENABLE                  (0U)
// USART2 诊断打印周期（毫秒），用于限制输出频率避免刷屏。
#define APP_USART2_DIAG_INTERVAL_MS             (500U)
// USART2 单次发送超时（毫秒），避免诊断输出长时间阻塞主循环。
#define APP_USART2_DIAG_TX_TIMEOUT_MS           (20U)

// 自检模式：1=暂停 RS485 从机通信，仅输出链路诊断信息。
// 量产/联调默认关闭（0），恢复正常从机通信路径。
#define APP_SELF_TEST_USE_USART1_DEBUG          (0U)

#endif
