/**
 * @file rs485_driver.h
 * @brief RS485 驱动对外接口声明
 *
 * 此文件声明 RS485 驱动对外 API，提供收发初始化、帧提取、异步发送和中断转发
 * 接口，供 Modbus 从机协议层调用。
 *
 * 主要内容：
 * - RS485 驱动初始化与启动接口
 * - 帧提取与发送接口
 * - USART/UART/TIM 中断回调接口
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#ifndef RS485_DRIVER_H
#define RS485_DRIVER_H

#include <stdbool.h>
#include <stdint.h>

#include "usart.h"

// RS485 驱动初始化：在 app_main_init() 中调用，绑定 UART 并复位状态。
// 参数：huart - UART 句柄（通常 &huart1）。
void rs485_driver_init(UART_HandleTypeDef *huart);

// RS485 驱动启动：在初始化后调用，开始 DMA 接收和 IDLE 中断。
void rs485_driver_start(void);

// USART IDLE 中断回调：在 modbus_slave_on_usart_idle_irq() 中调用，记录帧尾位置。
void rs485_driver_on_usart_idle_irq(void);

// UART 发送完成中断回调：在 modbus_slave_on_uart_tx_complete_irq() 中调用，进入后置延时。
// 参数：huart - UART 句柄。
void rs485_driver_on_uart_tx_complete_irq(UART_HandleTypeDef *huart);

// 静默 tick 中断回调：由 TIM2_CH1 周期触发，用于 3.5 字符静默判帧收敛。
void rs485_driver_on_silence_tick_irq(void);

// RS485 状态机轮询：在 modbus_slave_poll() 中调用，推进发送延时和 DE 切换。
void rs485_driver_poll(void);

// 提取完整帧：从环形缓冲区获取一帧数据。
// 参数：frame - 输出缓冲区；frame_buf_size - 缓冲区大小；frame_len - 输出帧长度。
// 返回：true=成功提取，false=无帧。
bool rs485_driver_fetch_frame(uint8_t *frame, uint16_t frame_buf_size, uint16_t *frame_len);

// 发送数据：异步启动 RS485 发送，包含前置延时。
// 参数：data - 发送数据；length - 数据长度。
// 返回：true=启动成功，false=忙碌或参数错误。
bool rs485_driver_send(const uint8_t *data, uint16_t length);

#endif
