/**
 * @file rs485_slave.h
 * @brief Modbus 从机协议模块接口声明
 *
 * 此文件声明 Modbus 从机协议层接口，负责主循环处理、请求响应分发和与 RS485
 * 驱动中断回调对接。
 *
 * 主要内容：
 * - 从机协议初始化与轮询接口
 * - USART IDLE 回调接口
 * - UART 发送完成与静默 tick 回调接口
 *
 * @author Generated by STM32CubeMX and customized
 * @date 2026-04-20
 */

#ifndef RS485_SLAVE_H
#define RS485_SLAVE_H

#include <stdint.h>

#include "usart.h"

// Modbus 从机模块初始化：在 app_main_init() 中调用，清零计数器。
void rs485_slave_init(void);

// Modbus 从机主循环：在 app_main_poll() 中调用，处理帧接收和响应。
void rs485_slave_poll(void);

// USART IDLE 中断回调：在 app_main_on_usart_idle_irq() 中调用，记录帧尾候选。
void rs485_slave_on_usart_idle_irq(void);

// UART 发送完成中断回调：在 app_main_on_uart_tx_cplt_irq() 中调用，推进发送状态机。
// 参数：huart - UART 句柄。
void rs485_slave_on_uart_tx_complete_irq(UART_HandleTypeDef *huart);

// 静默 tick 中断回调：在 app_main_on_tim2_oc_elapsed_irq() 中调用，累计帧结束计数。
void rs485_slave_on_silence_tick_irq(void);

#endif
